### ISSUE TITLE
Upgrade from 0.16 to 0.22. Connection refused when using OptsBuilder, but not Pool::from_url.

### ISSUE THREAD

**Issue by ragnese** [blackbeam/mysql_async#100]
Running a MySQL 5.7 server.

Old code that worked with version 0.16:
```
let mut opts_builder = OptsBuilder::new();
opts_builder
    .ip_or_hostname("localhost")
    .db_name(Some("my_db"))
    .user(Some("my_user"));
let pool = Pool::new(opts_builder);
```

With 0.22 I get a connection refused error. Using from_url works:
```
let pool = Pool::from_url("mysql://iq-controller@localhost:3306/iq_controller").unwrap();
```

**Comment by blackbeam** [comment]
Hi

As mentioned in the [release notes], methods of `OptsBuilder` are now by value, sob this should work:

```rust
let opts_builder = OptsBuilder::new()
    .ip_or_hostname("localhost")
    .db_name(Some("my_db"))
    .user(Some("my_user"));
let pool = Pool::new(opts_builder);
```

[release notes]: https://github.com/blackbeam/rust-mysql-simple/releases/tag/v18.0.0

**Comment by ragnese** [comment]
Oh! Thank you for that. I feel silly now! So, I was just passing a default OptsBuilder into Pool::new(). 👍

**Comment by ragnese** [comment]
I don't see that what you said is correct... In the docs, it still shows the builder methods taking mutable references and returning the same.

https://docs.rs/mysql_async/0.22.0/mysql_async/struct.OptsBuilder.html#method.user

**Comment by blackbeam** [comment]
Oh, sorry, i confused `mysql_async` with `mysql`.

I'll release 0.22.1 shortly.
