### ISSUE TITLE
mysql or mysql_async when using tokio+warp 

### ISSUE THREAD

**Issue by nbari** [blackbeam/mysql_async#104]
I am testing `warp` and currently using the `mysql` create with `Arc` something like this:

```
let pool =  mysql::Pool::new_manual(pool_min, pool_max, opts).unwrap_or_else(|e| {
        eprintln!("Could not connect to MySQL: {}", e);
        process::exit(1);
    })

let db = Arc::new(Mutex::new(pool));
let db = warp::any().map(move || Arc::clone(&db));

let register = warp::post()
        .and(warp::path("register"))
        .and(warp::body::json())
        .and(db.clone())
        .and_then(register);

warp::serve(register).run(([0, 0, 0, 0], 8000)).await;
```

So far all good, but I would like to know what could be the advantage of using `mysql_async` in this scenario.

For my current test case, based on the status of the query, I would return for example an HTTP 200 or  500 in either case I have to wait for the query to finish.

 If using `mysql_async` since I have to wait for the result of the query wondering what could be the advantage?

Sorry if this is too basic but I am trying to grasp my head around "async " and try to get a better understanding, currently I have some code using `mysql` and maybe I could continue using it by just using `Arc` and no need to change to `mysql_async`

**Comment by blackbeam** [comment]
> So far all good, but I would like to know what could be the advantage of using `mysql_async` in this scenario.

`mysql` is synchronous so IO, performed by `mysql`, will block async IO within tokio runtime (i believe the actual behavior depends on whether the basic or threaded tokio scheduler is in use).
Usually this is considered as a bad practice.

I heard earlier, that other synchronous drivers are oftenly used in async environment, viz. i heard about `diesel` + `hyper` where diesel queries are performed in tokio-threadpool, so async IO isn't blocked. Modern tokio versions have special method for this scenario ([`spawn_blocking`][1]). In theory, you should be able to handle more HTTP queries if all your IO is async (i.e using `mysql_async`), but it might be OK for you to simply call `mysql` using `spawn_blocking`.

> I am testing warp and currently using the mysql create with Arc something like this

Note, that `mysql::Pool` is [already an `Arc<Mutex<..>>`][2], so it's redundant to wrap it again.

[1]: https://docs.rs/tokio/0.2.13/tokio/task/fn.spawn_blocking.html
[2]: https://github.com/blackbeam/rust-mysql-simple/blob/master/src/conn/pool.rs#L96

**Comment by nbari** [comment]
Hi @blackbeam many thanks 👍
