### ISSUE TITLE
Err(Driver(ConnectionClosed)) 

### ISSUE THREAD

**Issue by nbari** [blackbeam/mysql_async#105]
Hi, I am trying `mysql_async` with `warp` something like this:

The pool:

```
let mut opts = mysql_async::OptsBuilder::new();
    opts.user(dsn.username);
    opts.pass(dsn.password.clone());
    opts.ip_or_hostname(dsn.host.unwrap());
    opts.socket(dsn.socket);
    opts.db_name(dsn.database);
    if let Some(port) = dsn.port {
        opts.tcp_port(port);
    }
    opts.pool_options(mysql_async::PoolOptions::with_constraints(
        mysql_async::PoolConstraints::new(10, 100).unwrap(),
    ));

    // mysql ssl options
    let mut ssl_opts = mysql_async::SslOpts::default();
    if let Some(tls) = dsn.params.get("tls") {
        if *tls == "skip-verify" {
            ssl_opts.set_danger_accept_invalid_certs(true);
        }
    }
    opts.ssl_opts(ssl_opts);

    mysql_async::Pool::new(opts)
```

Then with warp:

```
let pool = options::new();
    pool.get_conn().await.unwrap_or_else(|e| {
        eprintln!("Could not connect to MySQL: {}", e);
        process::exit(1);
    });
    println!("{:#?}", pool);

 let db = warp::any().map(move || pool.clone());

    let register = warp::post()
        .and(warp::path("register"))
        .and(warp::body::json())
        .and(db.clone())
        .and_then(register);

    warp::serve(register).run(([0, 0, 0, 0], 8000)).await;


async fn register(
    user: User,
    pool: mysql_async::Pool,
) -> Result<impl warp::Reply, warp::Rejection> {
 match queries::find_user(pool.clone(), &user.username, &user.email).await {
        Ok(rs) => {
             println!("{:?}", rs);
             Ok(StatusCode::CREATED)
       }
        err => {
            eprintln!("{:?}", err);
           Ok(StatusCode::INTERNAL_SERVER_ERROR)
        }
    }
}
```

and queries is something like:

```
pub async fn find_user(
    pool: mysql_async::Pool,
    username: &str,
    email: &str,
) -> Result<usize, Box<dyn Error>> {
    let conn = pool.get_conn().await?;
    let (_, row) = conn
        .first_exec::<_,_,usize>(
            "SELECT IF((SELECT count(*) FROM users WHERE email=?), 2, (IF((SELECT count(*) FROM users WHERE name=?), 1, 0)))",
            (&email, &username),
        ).await?;
    Ok(row.ok_or("expecting a row")?)
}
```

It works but in some cases, I am getting an `Err(Driver(ConnectionClosed))`, also the pool is always one connection instead of 10 as defined, therefore wondering what could be wrong or if I should close the connection after every use.

Any ideas?

**Comment by blackbeam** [comment]
Hi.

I've just tried something similar without issues (see [gist][1]). Pool started with one connection and finished with 10 simultaneous connections as expected (because of the default `min` constraint).

**Comment by nbari** [comment]
hi @blackbeam the gist URL missing

**Comment by nbari** [comment]
After you test, if you let the service up and running and try after a minute still working?

I have noticed that after sending the request if I test after some minutes, the pool is lost and needs to reconnect but the first requests get the `ConnectionClosed`, looks like the pool is not persistent or keeping the connection to the DB alive.

**Comment by blackbeam** [comment]
It's OK for me after about an hour.

Can you please share the result of `SELECT @@wait_timeout;` query on your mysql server?

**Comment by nbari** [comment]
Hi @blackbeam, it is set to `160`.

**Comment by blackbeam** [comment]
@nbari, thanks for report!

There is definitely an issue, because [this check][1] is missing since v0.22.0

[1]: https://github.com/blackbeam/mysql_async/blob/v0.21.0/src/conn/pool/mod.rs#L254

**Comment by blackbeam** [comment]
Please update to [v0.22.2](https://github.com/blackbeam/mysql_async/releases/tag/v0.22.2)?

**Comment by nbari** [comment]
Hi @blackbeam thanks for the quick fix, I will test and let you know how it goes

**Comment by nbari** [comment]
@blackbeam,  this is my output of `println!("{:#?}", pool);`:

```
Pool {
    opts: Opts {
        inner: InnerOpts {
            mysql_opts: MysqlOpts {
                user: Some(
                    "test",
                ),
                pass: Some(
                    "secret",
                ),
                db_name: Some(
                    "foo",
                ),
                tcp_keepalive: None,
                tcp_nodelay: true,
                local_infile_handler: None,
                pool_options: PoolOptions {
                    constraints: PoolConstraints {
                        min: 10,
                        max: 50,
                    },
                    inactive_connection_ttl: 0ns,
                    ttl_check_interval: 30s,
                },
                conn_ttl: Some(
                    60s,
                ),
                init: [],
                stmt_cache_size: 10,
                ssl_opts: Some(
                    SslOpts {
                        pkcs12_path: None,
                        password: None,
                        root_cert_path: None,
                        skip_domain_validation: false,
                        accept_invalid_certs: true,
                    },
                ),
                prefer_socket: true,
                socket: None,
                compression: None,
            },
            address: HostPort(
                "localhost",
                3306,
            ),
        },
    },
}
```

What I confirm and is working is that after `60` seconds as defined by the `conn_ttl` the connections are closed and when a new request is made the "pool" reconnects and fetches the results 👍 

But either I do 1 request or 1000 (like in your gist with ab) I never see one that more connections from the server-side, I tested with `mysql create` against the same MySQL server and it works as expected, but for some reason, `mysql_async` only creates 1 connection not a pool of connections.

**Comment by blackbeam** [comment]
> But either I do 1 request or 1000 (like in your gist with ab) I never see one that more connections from the server-side, I tested with mysql create against the same MySQL server and it works as expected, but for some reason, mysql_async only creates 1 connection not a pool of connections.

Please Note, that `mysql::Pool` will initialize itself eagerly, but `myslq_async::Pool` will not. To fill `myslq_async::Pool` to its `min` boundary you need to perform `min` queries at the same time, i.e. number of requests doesn't play any role in this, but concurrency (`-c` argument of `ab`) does.

Also note, that your `wait_timeout` is 160, so server will drop all connection, that idling longer.

**Comment by nbari** [comment]
I just tested with `wrk -c100 -d1m -t2 http://0:8000` and got the expected results, many thanks 👍
