### ISSUE TITLE
Bump up `mysql_common` dependency in 0.23.x ?

### ISSUE THREAD

**Issue by jonathanGB** [blackbeam/mysql_async#115]
Would it be possible to have a version of `mysql_async-0.23.x` depend on `mysql_common-0.22.0`? I see that `mysql_common-0.22.0` is the most recent version, but it is only used in `mysql_async-0.24`, which is in alpha.

Thanks!

**Comment by blackbeam** [comment]
Hi.

Looks like semver spec allows it, so yes.

**Comment by blackbeam** [comment]
Published as v0.23.1
