### ISSUE TITLE
UnknownParameter { param: "serverTimezone" }

### ISSUE THREAD

**Issue by llxxbb** [blackbeam/mysql_async#120]
Hello, I use "mysql://root@localhost/nature?serverTimezone=Asia/Shanghai" to connect my mariadb, it doesn't work and give me the message : UnknownParameter { param: "serverTimezone" }.
Before use `serverTimezone` it works fine, so I think it's a problem for TimeZone.

**Comment by blackbeam** [comment]
Hi. There is no such URL parameter in `mysql_async`.
I suggest you to execute `SET time_zone = 'Asia/Shanghai'` explicitly, or using 
[`OptsBuilder::init`][1].

[1]: https://docs.rs/mysql_async/0.24.0/mysql_async/struct.OptsBuilder.html#method.init

**Comment by blackbeam** [comment]
Closed due to inactivity. Feel free to reopen.
