### ISSUE TITLE
Empty result sets drop columns before they can be read

### ISSUE THREAD

**Issue by IvanChepurnyi** [blackbeam/mysql_async#121]
When you have multiple results sets in the query that return empty rows it is impossible to access current result set columns as it gets consumed before you can call columns method.

I'll try to provide a PR for making it possible to see if `next` can be split into multiple methods to return old meta when old one gets discarded. 

Here is a source of the problem:
1. When the next result set is received, it takes another loop run [here](https://github.com/blackbeam/mysql_async/blob/master/src/queryable/query_result.rs#L118-L122)
2. And on the next loop iteration it right away discards the result and returns `None` [here](https://github.com/blackbeam/mysql_async/blob/master/src/queryable/query_result.rs#L106-L109). 

It results in a situation that it is possible to fetch columns only of the first result set, but the rest of the result set is just skipped.

**Comment by blackbeam** [comment]
Fix published in [v0.24.2](https://github.com/blackbeam/mysql_async/releases/tag/v0.24.2)
