### ISSUE TITLE
Panic on: call to `stream_mut` on invalid connection

### ISSUE THREAD

**Issue by glyphpoch** [blackbeam/mysql_async#124]
Hello,

not sure if I'm misusing the library, if the database config needs tweeking or if I'm just trying to transfer too much data at once but I occassionally run into a panic, triggered by an `expect` in the `ConnInner::stream_mut` implementation.

The problem that we were trying to solve was that when an IO error occurred it was impossible to re-use the connection on which this occurred (originally it was the following error - `"EOF while reading length-encoded string"`, coming from `mysql_common`).

After the IO error, the connection somehow ended up broken, and any query executed on it always returned that IO error but it was never removed from the connection pool. The issue was discovered by one of my coworkers and I've had no luck reproducing it for some reason so the (temporary) workaround was to manually `disconnect` the connection when an IO error occurred...

This however led to a different problem, the `stream_mut` panic mentioned above.

### Environment:
```
MariaDB 10.1.31 (docker, default config)
Linux 4.14.86-gentoo
Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz (24 cores)
```

### Reproduction steps:
Pretty broken example but it's very difficult to reproduce in a normal environment..

#### Database schema
```sql
CREATE DATABASE testing;

CREATE TABLE random_data (
    id BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    data LONGBLOB
);
```

#### Test data
```bash
# Data:
head -c 1M </dev/urandom > /tmp/data.bin

echo "INSERT INTO testing.random_data (data) VALUES (LOAD_FILE('/tmp/big.bin'));" | mysql -p

# duplicate the data about 100 times
INSERT INTO random_data (data) SELECT data FROM random_data WHERE id = 0;
# ...

# Decrease the wait timeout to make connection closed errors more likely to occur
SET GLOBAL wait_timeout=2;
```

#### Code
```rust
use std::sync::Arc;

use tokio::sync::Mutex;

use mysql_async::prelude::*;

#[tokio::main(core_threads=20)]
async fn main() {
    let database_url = std::env::var("DATABASE_URL").unwrap();

    let pool = mysql_async::Pool::from_url(&database_url).unwrap();

    let mut tasks = vec![];
    let placeholder = Arc::new(Mutex::new(0u64));

    // Spawn 1000 tasks
    for _ in 0..1000 {
        let pool = pool.clone();
        let placeholder = placeholder.clone();

        let task = tokio::spawn(async move {
            let mut c: mysql_async::Conn;
            loop {
                let cr = pool.get_conn().await;
                match cr {
                    Ok(conn) => {
                        c = conn;
                        break;
                    },
                    Err(e) => {
                        println!("failed to get connection");
                    }
                }
            };

            let result: mysql_async::Result<Vec<Vec<u8>>> = c.query("SELECT data FROM random_data;").await;

            match result {
                Ok(s) => {
                    let mut placeholder = placeholder.lock().await;
                    *placeholder = placeholder.wrapping_add(s.len() as u64)
                },
                Err(mysql_async::Error::Io(e)) => {
                    println!("Err: {}", e);
                    // Disconnect the connection on Io errors
                    let _ = c.disconnect().await;
                },
                _ => {},
            }
        });
        tasks.push(task);
    }

    futures::future::join_all(tasks).await;

    let _ = pool.disconnect().await;

    println!("placeholder count: {}", placeholder.lock().await);
}
```

```toml
[dependencies]
mysql_async = "0.24.1"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
```

```bash
export DATABASE_URL="mysql://root:password@127.0.0.1:3306/testing"
```

#### Example output
```
Err: Input/output error: connection closed
thread 'tokio-runtime-worker' panicked at 'call to stream_mut on invalid connection', /home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql_async-0.24.1/src/conn/mod.rs:143:9
Err: Input/output error: connection closed
thread 'tokio-runtime-worker' panicked at 'call to stream_mut on invalid connection', /home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql_async-0.24.1/src/conn/mod.rs:143:9
Err: Input/output error: connection closed
...
...
...
thread 'tokio-runtime-worker' panicked at 'assertion failed: `(left == right)`
  left: `9`,
 right: `0`', /home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql_async-0.24.1/src/conn/pool/recycler.rs:208:13
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql_async-0.24.1/src/conn/pool/futures/disconnect_pool.rs:44:28
```

**Comment by blackbeam** [comment]
Oh, thanks for detailed report!
I'll look into it as soon as i can.

**Comment by blackbeam** [comment]
Well, I found two problems (see #125):

1. The `call to stream_mut on invalid connection` panic definitely should not happen, so I've replaced it with the new `ConnectionClosed` error;
2. `Conn::disconnect` did not check that connection was already disconnected.

> The problem that we were trying to solve was that when an IO error occurred it was impossible to re-use the connection on which this occurred (originally it was the following error - "EOF while reading length-encoded string", coming from mysql_common).

Errors like this from `mysql_async` usually means either protocol implementation bug or that there is something wrong with the connection. In either case, you can't simply reuse the connection because it's broken (completely). I believe the rule of thumb for query errors is the following:

*   the error is `Error::Server(_)` – you can reuse the connection;
*   any other error – you must drop the connection and reconnect.

**Comment by glyphpoch** [comment]
Ah cool, the reproduction example works well with this fix now.

> In either case, you can't simply reuse the connection because it's broken (completely) ...

Thanks for clearing that up, I assumed it would be enough to `disconnect` on `Io` and `Driver` errors and leave the connection open in all the other cases.

And thanks for the fix, looks good!

**Comment by blackbeam** [comment]
Fix published in [v0.24.2](https://github.com/blackbeam/mysql_async/releases/tag/v0.24.2)

**Comment by rohitjoshi** [comment]
I am seeing similar error in v0.25
```
thread 'xxx-db-async' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql_async-0.25.0/src/conn/pool/mod.rs:227:55
```

**Comment by blackbeam** [comment]
Looks like there was another thread that panicked just before this one.
