### ISSUE TITLE
failed to fill whole buffer

### ISSUE THREAD

**Issue by DrYaling** [blackbeam/mysql_async#134]
Hi!
I meet a problem while executing transaction exec_drop,some times I got error result like:
     Io(Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }))
But when i tried again,it's just ok.

On version 0.25.0
my code like this:
trans.exec_drop(
                "INSERT INTO stock_order_sku (order_id,sku_id,amount) VALUES(?,?,?)",
                (order_id, sku, amount),
            ).await.map_err(|e| error!("fail to insert sku info {:?}",e))
            .is_ok();

**Comment by blackbeam** [comment]
Hi.

Could you please tell me which types do `order_id`, `sku` and `amount` have? And also your mysql server version? I'll fuzz it.

**Comment by DrYaling** [comment]
sure. order_id and sku are String, and amount is i32
this is the function called
pub async fn import_product_stock_order_complete(
    trans: &mut Transaction<'_>,
    stock_order_id: &String,
    sku: &Vec<(String /*id*/, i32 /*amount*/)>,
) -> Result<(),String> {
    let _e = utils::TimeEscape::build_drop("stock complete",5);
    let mut ok = false;
    for (_id, amount) in sku {
        ok = trans.exec_drop(
                "INSERT INTO stock_order_sku (order_id,sku_id,amount) VALUES(?,?,?)",
                (stock_order_id, _id, amount),
            ).await.map_err(|e| error!("fail to insert sku info {:?}",e))
            .is_ok();
        if !ok {
            break;
        }
    }
    if ok {
        info!(
            "insert stock_order_sku for stock order id {},sku {:?}",
            stock_order_id, sku
        );
        Ok(())
    } else {
        error!(
            "fail to insert stock_order_sku for stock order id {},sku {:?}",
            stock_order_id, sku
        );
        Err("fail to insert stock order sku".to_owned())
    }    
}

**Comment by DrYaling** [comment]
And thanks for reply so soon!

**Comment by blackbeam** [comment]
Could you please also share the `stock_order_sku` table definition?

**Comment by DrYaling** [comment]
Sure,here is it:
`
CREATE TABLE `stock_order_sku` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
	`order_id` VARCHAR(50) NOT NULL COMMENT 'order ID',
	`sku_id` VARCHAR(60) NOT NULL COMMENT 'sku',
	`amount` INT(10) UNSIGNED NOT NULL COMMENT 'sku amount',
	`updated_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'time created or updated',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `order_sku_index` (`order_id`, `sku_id`),
	INDEX `FK_prod_stock_order_id` (`order_id`)
)
COMMENT='stock order info'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
`

**Comment by DrYaling** [comment]
FK_prod_stock_order_id  was unused, just remove it

**Comment by DrYaling** [comment]
And futher more,this transaction was created by mysql_async:Conn from mysql_async::Pool

**Comment by blackbeam** [comment]
So far fuzzing goes without errors.

Is there some custom mysql configuration in use?
On what OS your server running?
Whether client local or remote for your mysql server?

**Comment by DrYaling** [comment]
My OS is Windows7 profitional,24GB RAM,client is running on this OS.
Mysql server is running on :
  Linux bytest 3.10.0-862.el7.x86_64
  CentOS Linux release 7.5.1804
It's fuzz me much.My service was using mysql lib prety good with config: mysql = "16.1".
But when switch to mysql_async,till now, three errors reported as bellow:
  1.Io(Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }))
  2.Io(Io(Custom { kind: Other, error: "packet out of order" }))
  3.Io(Io(Custom { kind: InvalidData, error: "Invalid statement packet status" }))
The 1st and 3ird occurs while try to do exec action,and the 2nd occurs while did the prevous action or when opening a transaction.
But all this errors seems hard to reproduce,I tried many times and can't find the case to reproduce.
And it seems easier to reproduce when my client was restarted,expecially for 2nd error.

**Comment by DrYaling** [comment]
This file was the pool manager for Conn:
[sql_pool.txt](https://github.com/blackbeam/mysql_async/files/5522510/sql_pool.txt)

**Comment by DrYaling** [comment]
Hope this may give some help:
I start my client and did nothing until mins(or tens) later,then my sql query result out :
   Io(Io(Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }))
And this situation occurs twice for me.
