### ISSUE TITLE
query_map description seems wrong

### ISSUE THREAD

**Issue by malaire** [blackbeam/mysql_async#135]
`query_map` description says "Performs the given query and returns the first row of the first result set", but as it returns `Vec` it looks like it returns all rows and not just first row?

https://github.com/blackbeam/mysql_async/blob/a1aa78893458ef1d82794d5cf84a18ddec8a29e4/src/queryable/mod.rs#L159

**Comment by blackbeam** [comment]
Oh. A copy-paste error.
Thanks for pointing this out.
