### ISSUE TITLE
QueryResult::affected_rows() always returns 1

### ISSUE THREAD

**Issue by KOBA789** [blackbeam/mysql_async#14]
`QueryResult::affected_rows()` always returns `1` only.

I explored some codes, but I couldn't find out what's wrong. It seems ok 🤔  :
https://github.com/blackbeam/mysql_async/blob/410653d10a8b5023c5e0b7d3a3f4bc1684158729/src/proto.rs#L589-L590

Any idea?

**Comment by blackbeam** [comment]
Hi!

Just tried this test, and it looks like everything ok:

```rust
#[test]
fn should_correctly_handle_affected_rows() {
    let mut lp = Core::new().unwrap();

    let fut = Conn::new(get_opts(), &lp.handle())
        .and_then(|conn| {
            conn.drop_query("CREATE TEMPORARY TABLE tmp (name text)")
        })
        .and_then(|conn| {
            Queryable::drop_query(conn, "INSERT INTO tmp VALUES ('foo')")
        })
        .and_then(|conn| {
            Queryable::drop_query(conn, "INSERT INTO tmp VALUES ('bar')")
        })
        .and_then(|conn| {
            Queryable::query(conn, "UPDATE tmp SET name = 'baz'")
        })
        .and_then(|result| {
            assert_eq!(result.affected_rows(), 2);
            result.drop_result()
        })
        .and_then(|conn| conn.disconnect());

    let result = lp.run(fut).unwrap();
}
```

Could you give more details?

**Comment by KOBA789** [comment]
It was my misunderstanding.

I executed the SELECT statement with `prep_exec`, so in this case, `affected_rows` always returns 1.
However, it's nonsense to use `affected_rows` for SELECT statement.

Thank you for explanation.
