### ISSUE TITLE
Include "vendored" flag for TLS

### ISSUE THREAD

**Issue by NAlexPear** [blackbeam/mysql_async#143]
In my current fork of `mysql_async`, I've [set the "vendored" flag on the `native-tls` dependency](https://github.com/NAlexPear/mysql_async/blob/master/Cargo.toml#L23) to enable statically-compiled binaries for `musl` environments (specifically, `alpine` Linux).

Would you be open to a PR that added a `vendored` or `tls-vendored` feature flag to `mysql_async` to handle this case?

**Comment by blackbeam** [comment]
Hi, Alex.

Similar issue appeared earlier, I believe 🤔. Anyway, you can simply add `native-tls` (with the `vendored` feature enabled) as a dependency you your project next to `mysql_async`. This should do the job.

**Comment by blackbeam** [comment]
> similar issue appeared earlier

It was in `mysql` crate: https://github.com/blackbeam/rust-mysql-simple/pull/238
