### ISSUE TITLE
FromRow with more than arity 12

### ISSUE THREAD

**Issue by DonghunLouisLee** [blackbeam/mysql_async#144]
I have a table which has more than 12 fields(around 17 to be exact) but the current implementation for FromRow only supports upto maximum arity 12. I was wondering if the hard coded fromrow implementation for all arities are necessary?  Is it possible to take in flexible number of arguments?

Thanks in advance

**Comment by blackbeam** [comment]
Hi.

Please use the [`Row`][1] type.

Related issues:

* blackbeam/rust-mysql-simple#223
* blackbeam/rust-mysql-simple#137
* blackbeam/rust_mysql_common#9

[1]: https://docs.rs/mysql_async/0.26.0/mysql_async/struct.Row.html
