### ISSUE TITLE
OS error code 22

### ISSUE THREAD

**Issue by tomleavy** [blackbeam/mysql_async#145]
I have been testing the library for a highly parallelized application using Tokio. I have the Tokio runtime using 8 worker threads, and I noticed that when running inside for_each_concurrent I randomly receive an error 

`Error: MySql(Io(Io(Os { code: 22, kind: InvalidInput, message: "Invalid argument" })))`

Any idea why this error is coming up? I set the min and max pool connections to 8. I don't see any errors in the MySQL db error log

`mysql://root@localhost/mydb?pool_min=8&pool_max=8`

In general my code calls `get_conn`on the pool inside each function that executes a query

**Comment by blackbeam** [comment]
Hi.
Which _platform/server version/create version_ do you use?

**Comment by tomleavy** [comment]
Rust 1.49
mysql_async 0.26
macOS 11.1 with MySQL 8

It seems the issue is that by running everything in a for_each_concurrent loop where tokio is multithreaded that there is a race condition that triggers the connection pool to go beyond its limit or something. I ran the exact same code using sqlx and did not get any errors

**Comment by blackbeam** [comment]
@tomleavy, could you please try to reproduce it on `mysql_async` v0.25.1?

**Comment by tomleavy** [comment]
My code all relies on Tokio 1.1, which I believe is a problem. Easiest way for you to test this is to make an async function that inside gets a connection from the pool and executes a query, and then call that async function inside `for_each_concurrent` loop with max parallelism to the same # of threads the Tokio runtime has for worker threads. I used 8

**Comment by blackbeam** [comment]
I couldn't reproduce it, unfortunately.

**Comment by tomleavy** [comment]
All good, maybe something specific to my code. Thanks for looking into it!
