### ISSUE TITLE
Resolving has some weird race condition

### ISSUE THREAD

**Issue by pimeys** [blackbeam/mysql_async#146]
Hi. Something interesting happened with Docker recently that they don't answer to `::1` anymore, although `127.0.0.1` and `0.0.0.0` work.

This means in our test setup, where we connect to docker with tokio-postgres, mysql_async and tiberius, some of the connections started to error out. I started debugging, and with tiberius we just resolved the first address, got `::1` and stopped there. That's fixed now in here: https://github.com/prisma/tiberius/pull/124

tokio-postgres does it as we do in tiberius by [looping the addresses in sequence](https://github.com/sfackler/rust-postgres/blob/master/tokio-postgres/src/connect_socket.rs#L32) and we could always connect to docker postgres with localhost.

Now, in this crate, we seem to race all addresses and get the first that works for our connection. What I see when I debugged master code a bit is that we get to [this point in code](https://github.com/blackbeam/mysql_async/blob/master/src/io/mod.rs#L412-L416) with a resolved address `::1`, which later on gives us `connection refused`.

I don't know this part of the code that well to be able quickly fix anything, but should `connect_stream(address, keepalive_opts.clone())` give us an error if we cannot connect to the IP address, and then the other future we're racing with to `127.0.0.1` be used due to it working?

**Comment by janpio** [comment]
We could confirm that #147 that @pimeys created solved that problem for us.

**Comment by blackbeam** [comment]
Published as [v0.27.0](https://github.com/blackbeam/mysql_async/releases/tag/v0.27.0). Thanks!
