### ISSUE TITLE
How to move to next result set?

### ISSUE THREAD

**Issue by kingluo** [blackbeam/mysql_async#152]
It seems to no example or API, So confused.

**Comment by blackbeam** [comment]
Hi. You can call the `collect` method (or any other combinator) once for each result set. Please see [corresponding docs](https://docs.rs/mysql_async/0.27.1/mysql_async/struct.QueryResult.html#method.collect).

**Comment by kingluo** [comment]
No streaming way? If the returning result set is large.

**Comment by blackbeam** [comment]
> No streaming way? If the returning result set is large.

For large result sets you can use `for_each` or `reduce`.

**Comment by kingluo** [comment]
Does the result is streaming in the background? I mean, read packets from network on demand.

**Comment by blackbeam** [comment]
Yeah
