### ISSUE TITLE
Upgrading from 0.27.1 to 0.28.0 my program panics on strings

### ISSUE THREAD

**Issue by nappa85** [blackbeam/mysql_async#162]
My program still works fine with 0.27.1, if I use 0.28.0 I got a panic at runtime:
```
thread 'tokio-runtime-worker' panicked at 'Could not retrieve alloc::string::String from Value', /home/marco/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql_common-0.27.3/src/value/convert/mod.rs:173:23
```
the panicking row is a simple
```rust
let symbol = row.take("symbol").ok_or_else(|| error!("missing symbol field"))?;
```
the table field `symbol` is a varchar(255) latin1 field and cant' be NULL, the content is valid, I checked it myself.

Can it be a regression?

**Comment by blackbeam** [comment]
Hi. I've already ported few projects to v0.28.0 and found no similar issues, so It might be hard to reproduce without knowing the actual value. Could you please share it?

```rust
match row.take::<Value, _>("symbol") {
    Some(Value::Bytes(bytes)) => println!("The content is {:?}", bytes),
    x => panic!("not a string {:?}", x),
}
```

**Comment by blackbeam** [comment]
Could you please invoke `cargo update` to bump mysql_common to v0.27.4? This might fix the issue.

**Comment by nappa85** [comment]
> Hi. I've already ported few projects to v0.28.0 and found no similar issues, so It might be hard to reproduce without knowing the actual value. Could you please share it?
> 
> ```rust
> match row.take::<Value, _>("symbol") {
>     Some(Value::Bytes(bytes)) => println!("The content is {:?}", bytes),
>     x => panic!("not a string {:?}", x),
> }
> ```

It's a Value::Null, but the value in DB isn't Null, the column is NOT NULL.

**Comment by nappa85** [comment]
> Could you please invoke `cargo update` to bump mysql_common to v0.27.4? This might fix the issue.

I can confirm that upgrading to mysql_common 0.27.4 solves the issue

**Comment by blackbeam** [comment]
Great! Thanks.
