### ISSUE TITLE
BufferPool is extremely slow under contention

### ISSUE THREAD

**Issue by vkrasnov** [blackbeam/mysql_async#169]
I am running a highly concurrent MySQL client and the Mutex contention in BufferPool leads to extreme slowdown.

I tried replacing the `Mutex<Vec<_>>` `with crossbeam::queue::ArrayQueue` and it led to a 4 fold performance improvement (in terms of QPS). I don't really see any downsides in using `ArrayQueue` even under low load, so if you would consider it I will be more than happy to open a pull request.

Thanks.

**Comment by blackbeam** [comment]
Thanks! Yeah, PRs are much appreciated.
