### ISSUE TITLE
Opts isn't Send because of LocalInfileHandlerObject

### ISSUE THREAD

**Issue by jonhoo** [blackbeam/mysql_async#17]
Currently, it is impossible to establish a `Conn`, or even just construct an `Opts`, in one thread, and then pass that to another, because `Opts` is not `Send`. This kind of setup is fairly common in applications using worker-pools, but is impossible with `mysql_async` today. In particular, it looks like `Opts` is not `Send` due to its `Option<LocalInfileHandlerObject>`. `LocalInfileHandlerObject` is not `Send` because the wrapped `LocalInfileHandler` is not `Sync` (`Arc<T>` is only `Send` if `T: Sync + Send`). I *think* it should be sufficient to have `LocalInfileHandler` require `Self: Sync + Send`, though I don't know if that restriction is okay to require?

**Comment by blackbeam** [comment]
Hi.

I tried to make Conn satisfy Send before LocalInfileHandler was implemented, but end up with rustc fell into recursion while trying to render compilation errors.

I'll look into it again.

**Comment by jonhoo** [comment]
Have you had any luck looking into this? It keeps coming back to bite me whenever I want to use this crate with connections in more than one thread :)

**Comment by jonhoo** [comment]
For what it's worth, `Opts` is indeed `Send` without `LocalInfileHandler` now: https://github.com/jonhoo/mysql_async/commit/cbd03d62fb35dfb823bb234d27d6cc5484ae8d35. Unfortunately, while attractive, we can't just change

https://github.com/blackbeam/mysql_async/blob/master/src/local_infile_handler/mod.rs#L71

to have `: Send + Sync` bounds. The `impl Send` [for `Arc`](https://doc.rust-lang.org/std/sync/struct.Arc.html#impl-Send) would then kick in to make `LocalInfileHandlerObject: Send`, but the [`impl for WhiteListFsLocalInfileHandler`](https://github.com/blackbeam/mysql_async/blob/master/src/local_infile_handler/builtin.rs#L183) would no longer work since `tokio_core::Handler` is neither `Send` nor `Sync`. Not sure how to get that to work without making `Opts` generic over `T: LocalInfileHandler` :/

One compromise that might work is to make `Opts` (and `OptsBuilder`) generic over `T: LocalInfileHandler`, but set a default with:

```rust
struct Opts<T = WhiteListFsLocalInfileHandler> where T: LocalInfileHandler {
  // ...
}
```

And then provide some other impl of `LocalInfileHandler`, say `DenyLocalInfileHandler`, which refuses to read any file (and since it has no inner fields, it can be `Send`).

**Comment by blackbeam** [comment]
I've changed `WhiteListFsLocalInfileHandler` to store `Remote` instead of `Handle` (see e0444a9 in **sync-opts** branch). Also i've added `Sync + Send` bounds to `LocalInfileHandler` (see 415c86f in **sync-opts** branch).

[Looks like](https://github.com/tokio-rs/tokio-core/issues/43#issuecomment-249733088) `Conn` and `Pool` should also store `Remote` instead of `Handle` to be `Send + Sync`. I'll try to replace it.

**Comment by blackbeam** [comment]
`Conn`, which is not send, was leading to inconvenience with old hyper (hyperium/hyper#1063), but [looks like](https://github.com/hyperium/hyper/commit/16e834d37cfa636f781dee3cb5bb456691fb789b) it's not an issue any more.

> I think it is more okay for `Conn` and `Pool` to not be `Send + Sync`.

Agree. Idea of using async library in multiple threads looks strange. If anybody wants to use async library in multiple threads, then he'd better to run another loop to not to pay for synchronization.

I think i'll merge **sync-opts** branch up to a701da4.

**Comment by jonhoo** [comment]
This probably also requires a version bump.

**Comment by blackbeam** [comment]
Yeah. Minor version will be bumped, since `LocalInfileHandler::handle` signature was changed. Will publish as 0.14.0.

**Comment by blackbeam** [comment]
[Published](https://github.com/blackbeam/mysql_async/releases/tag/v0.14.0) 🎉
