### ISSUE TITLE
Dropping pooled connection when panicking leads to resource leak

### ISSUE THREAD

**Issue by WGH-** [blackbeam/mysql_async#171]
As of now, `Drop` implementation for pooled connections begins with this:

https://github.com/blackbeam/mysql_async/blob/21ff2906e6273ccc89056a84a4c11eb7adec7977/src/conn/pool/mod.rs#L285-L297

This means that if connection is dropped when panicking, it's not released to pool in any way.

I know that panic is not the proper way to handle errors in Rust, but in practice, at least some of the web runtimes/frameworks (Rocket for example) have panic handlers, so they intercept them and return an internal server error. Which means that when an application has a bug that causes panic, it will not crash, but rather eventually (100 crashing requests by default) deadlock on taking new connection from the pool.

**Comment by blackbeam** [comment]
@WGH-, thanks for report. Could you please try [this branch](https://github.com/blackbeam/mysql_async/tree/issue-171-panicking-conn-drop)?

**Comment by WGH-** [comment]
It fixes the problem for me.

**Comment by blackbeam** [comment]
Great! Thanks.
Will be in the next release (soon).

**Comment by blackbeam** [comment]
Sorry for delay. Published in [v0.29.0](https://github.com/blackbeam/mysql_async/releases/tag/v0.29.0).
