### ISSUE TITLE
MySQL Common Version update

### ISSUE THREAD

**Issue by normano** [blackbeam/mysql_async#174]
https://github.com/blackbeam/mysql_async/blob/21ff2906e6273ccc89056a84a4c11eb7adec7977/Cargo.toml#L25

Above line in my opinion should be "^0" since it is the same library so you don't need to lock the version, but nevertheless will need a new release to use mysql_common 0.28.

**Comment by blackbeam** [comment]
Updated in [v0.29.0](https://github.com/blackbeam/mysql_async/releases/tag/v0.29.0)
