### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by c410-f3r** [blackbeam/mysql_async#177]
`mysql_async = { default-features = false, version = "0.29" }` is not building. Please ensure the minimum requirements to make `default-features = false` work

**Comment by blackbeam** [comment]
Hi. Sorry for this. I'll update the README.

For now please look at the last paragraph in the ["Crate Features"](https://github.com/blackbeam/rust-mysql-simple#crate-features) section of `mysql`'s README, because requirements are roughly the same.

**Comment by c410-f3r** [comment]
Closing due to the lack activeness. Feel free to re-open this issue if desired.
