### ISSUE TITLE
How to use LocalInfileHandler

### ISSUE THREAD

**Issue by cc-morning** [blackbeam/mysql_async#180]
Hi, I have an asynchronous stream how do I write to the database using LocalInfileHandler
![截图_2022-02-19_17-41-30](https://user-images.githubusercontent.com/90960002/154795603-c5a38011-5594-455c-9b6c-e2d78bd1e22c.png)
Vec is a line of data

**Comment by blackbeam** [comment]
Hi. Current implementation based on tokio's `AsyncRead` trait (see `InfileHandlerFuture`). If your infile data is a stream of vectors (i.e. chunked), then you need to make a wrapper that reads this stream and implements AsyncRead. Pinboxed version of this wrapper will be your `InfileHandlerFuture`.

**Comment by cc-morning** [comment]
Sorry to bother you again, I tried to convert `stream` to `AsyncReader` using `StreamReader` from `tokio-util`, but it was difficult to work with the strict trait requirements and lifecycle limitations, so I had to ask for help again

**Comment by blackbeam** [comment]
Hi.

You should consider the handler, as an `AsyncRead` factory. I.e. each call to `<ExampleHandler as LocalInfileHandler>::handle` should emit a future that eventually gives another `AsyncRead`.
In your case this means that your handler will either work only once (because you have to give away the `R`),
or it must satisfy `Copy` (but it won't).

Consider the following version (I wrote it blindly without diving my head into the meaning):

```rust
// the following code assumes, that the MySQL::reader() definition is changed to this:
pub async fn reader(&self) -> anyhow::Result<impl Stream<Item = std::io::Result<bytes::Bytes>>> {
// ....

#[tokio::test]
async fn test() -> anyhow::Result<()> {
    use serde_json::json;

    struct Handler(MySQL);

    impl LocalInfileHandler for Handler {
        fn handle(&self, _file_name: &[u8]) -> mysql_async::InfileHandlerFuture {
            let mysql = self.0.clone();
            Box::pin(async move {
                mysql
                    .reader()
                    .await
                    // turn Stream<Bytes> into AsyncRead
                    .map(StreamReader::new)
                    // Box::pin to satisfy InfileHandlerFuture definition
                    .map(|x| Box::new(Box::pin(x)) as Box<_>)
                    // map error to satisfy InfileHandlerFuture definition
                    .map_err(|e| mysql_async::Error::Other(e.to_string().into()))
            })
        }
    }

    let table = "test";
    let mysql = crate::from::mysql::MySQL::new(&json!({
        "url": "mysql://root:password@127.0.0.1/mysql",
        "table": table
    }));

    let opts = OptsBuilder::from_opts(Opts::from_url("mysql://root:root@127.0.0.1/river")?)
        .local_infile_handler(Some(Handler(mysql)));
    let pool = mysql_async::Pool::new(opts);

    Ok(())
}
```

**Comment by cc-morning** [comment]
Thanks, he can work. It was my problem, I shouldn't have passed the AsyncReader implementation directly, resulting in the AsyncReader needing to meet the unsolvable declaration cycle and trait
