### ISSUE TITLE
BLOB type detection not working with mariadb 10.7.1

### ISSUE THREAD

**Issue by andrieshiemstra** [blackbeam/mysql_async#181]
When checking column types all BLOB and TEXT columns are reported to be of type MYSQL_TYPE_BLOB instead of the correct types

# Cargo.toml
```toml
...
[dependencies]
mysql_async = "0.29"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
```

# main.rs

```rust
use std::error::Error;
use mysql_async::prelude::Queryable;
use mysql_async::{Row, Value};

async fn test() -> Result<(), Box<dyn Error>> {

    let pool = mysql_async::Pool::new("mysql://username:password@serverip:3306/databasename");

    let mut con = pool.get_conn().await?;

    let table_create = r#"
        CREATE TABLE IF NOT EXISTS `test_table` (
          `id` INT NOT NULL AUTO_INCREMENT,
          `b` BLOB NULL,
          `mb` MEDIUMBLOB NULL,
          `lb` LONGBLOB NULL,
          `t` TEXT NULL,
          `mt` MEDIUMTEXT NULL,
          `lt` LONGTEXT NULL,
          `json` JSON NULL,
          PRIMARY KEY (`id`)
        );
    "#;

    let stmt = con
        .prep(table_create)
        .await?;

    let params: Vec<Value> = vec![];
    let _res: Vec<Row> = con.exec(stmt, params).await?;

    let get_query = r#"
        SELECT * FROM test_table;
    "#;

    let get_stmt = con.prep(get_query).await?;

    for col in get_stmt.columns() {
        println!("name: {}, type: {:?}", col.name_str(), col.column_type());
    }

    Ok(())


}

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    test().await?;
    Ok(())
}

```

actual output:
```
name: id, type: MYSQL_TYPE_LONG
name: b, type: MYSQL_TYPE_BLOB
name: mb, type: MYSQL_TYPE_BLOB
name: lb, type: MYSQL_TYPE_BLOB
name: t, type: MYSQL_TYPE_BLOB
name: mt, type: MYSQL_TYPE_BLOB
name: lt, type: MYSQL_TYPE_BLOB
name: json, type: MYSQL_TYPE_BLOB
```

I noticed the ColumnType enum does not have the (LONG/MEDIUM)_TEXT types but it does have the different BLOB types..

I am unsure if this is mariadb related bug or applies to more mysql like servers

**Comment by andrieshiemstra** [comment]
PS,

As a workaround i check the ```col.column_length()``` u32 which is filled correctly with the size of the BLOB's but I have not yet figured out a way to detect TEXT type columns (so now in my project i only use MEDIUM_TEXT for TEXT and LONG_BLOB for BLOB)

**Comment by blackbeam** [comment]
Hi.

There is nothing I can do with this, since `MYSQL_TYPE_BLOB` is the type server reports (see bellow captured [ColumnDefinition](https://dev.mysql.com/doc/internals/en/com-query-response.html#packet-Protocol::ColumnDefinition) packets)

<details>
<summary>captured packets</summary>
<img width="539" alt="изображение" src="https://user-images.githubusercontent.com/155883/160288752-3ded8493-f501-4328-a32a-e3de96918a46.png">

</details>

I believe you should either look at `column_length` and `flags` fields of a column, or look at the table definition:

```
name: id, type: MYSQL_TYPE_LONG, column_length: 11, flags: NOT_NULL_FLAG | PRI_KEY_FLAG | AUTO_INCREMENT_FLAG | PART_KEY_FLAG
name: b, type: MYSQL_TYPE_BLOB, column_length: 65535, flags: BLOB_FLAG | BINARY_FLAG
name: mb, type: MYSQL_TYPE_BLOB, column_length: 16777215, flags: BLOB_FLAG | BINARY_FLAG
name: lb, type: MYSQL_TYPE_BLOB, column_length: 4294967295, flags: BLOB_FLAG | BINARY_FLAG
name: t, type: MYSQL_TYPE_BLOB, column_length: 262140, flags: BLOB_FLAG
name: mt, type: MYSQL_TYPE_BLOB, column_length: 67108860, flags: BLOB_FLAG
name: lt, type: MYSQL_TYPE_BLOB, column_length: 4294967295, flags: BLOB_FLAG
name: json, type: MYSQL_TYPE_JSON, column_length: 4294967295, flags: BLOB_FLAG | BINARY_FLAG
```

**Comment by blackbeam** [comment]
Please also look at [this page](https://dev.mysql.com/doc/c-api/5.7/en/c-api-data-structures.html), especially into a table describing possible values of the type field.

**Comment by andrieshiemstra** [comment]
oooh awesome, the flags() totaly saved my day :)

Thanks for all the info! and keep up the great work, love this project!
