### ISSUE TITLE
A way to set a maximum timeout to wait for a connection from the pool

### ISSUE THREAD

**Issue by ahmedriza** [blackbeam/mysql_async#183]
Is there a way to set a limit on the amount of time to wait in order to get a connection from the pool?

**Comment by blackbeam** [comment]
Hi. Have you tried https://docs.rs/tokio/0.1.22/tokio/timer/struct.Timeout.html ?

**Comment by ahmedriza** [comment]
@blackbeam works perfectly.  Thanks.
