### ISSUE TITLE
Relationship between Queryable and ToConnection?

### ISSUE THREAD

**Issue by ragnese** [blackbeam/mysql_async#186]
Thank you for the excellent library.

I was working with some of my older code when I realized that there are basically two ways to execute a query: With the Query as the receiver (e.g., `"SELECT * FROM foo;".fetch(conn)`), or with a Queryable as the receiver (e.g., `conn.query("SELECT * FROM foo;")').

But, there are different types involved. The query-receiver API needs `ToConnection` instances, and the queryable-receiver API needs `Queryable` instances.

In practice, we know that Pool, Conn, and Transaction are ToConnection; and that Conn, and Transaction are Queryable.

Since ToConnection is only there to get a Conn, and Conn is a Queryable, it may make sense to have ToConnection also be Queryable.

That would also provide a partial "bridge" between the different API styles.

Previously, I had written some functions to accept a Queryable so that it could be called with a Conn or a Transaction, but that limits me to one style of query syntax. I realize now that I could just always accept a Conn, and just have any transaction context pass in the Transaction's inner Conn. But that makes the call site more noisy. 

It would be really cool if I could write a function that would accept any of Conn, Transaction, or Pool as input, and be able to use whichever query syntax I felt like using that day.

So, maybe the answer to that would be for `ToConnection` to "inherit" `Queryable`.

Or is this all way off base?

**Comment by blackbeam** [comment]
Hi.

> Since ToConnection is only there to get a Conn, and Conn is a Queryable, it may make sense to have ToConnection also be Queryable.

`ToConnection` is one step behind `Queryable`. More precisely, it is only partially a `Queryable` (it is, when `ToConnection` is Immediate and its not, when `ToConnection` is Mediate. See `ToConnectionResult`). It won't be possible to define `Queryable` for the Mediate part because you'll need to give away `self` that is behind a mutable reference.

Regarding the `Query` trait, it was created to allow a caller to conveniently emit a `'static` futures. That's why `ToConnection` is consuming (`IntoConnection` would be more conventional name). It might be the case that `Queryable` is enough for you, but the `Query` is quite convenient for some cases:

```rust
impl Workstation {
    /// Returns a 'static stream of workstations matching the given filter.
    pub fn stream<T: ToConnection<'static, 'static> + 'static>(
        conn: T,
        filter: Option<SqlFilter<WsField>>,
        order: Option<Order<WsField>>,
    ) -> BoxStream<'static, crate::Result<Self>> {
        // ...
    }
}
```

**Comment by ragnese** [comment]
Thanks for the reply!

I did see that ToConnection has two states, but I assumed that since all of the Queryable stuff is Futures anyway, you could somehow implement it to return a Future that resolves whenever the connect is eventually available. But, now that you mention needing to consume `self`, I can understand why that wouldn't work.

> Regarding the Query trait, it was created to allow a caller to conveniently emit a 'static futures. 

Ah! Fair enough. I hadn't thought that there might actually be different capabilities between using Query vs. Queryable APIs, other than how you get one.

Thanks again. I've been happily using your mysql crates for several years. I just never really thought much about the traits/types involved until recently.
