### ISSUE TITLE
Is it considered to add an easy to use `load data`

### ISSUE THREAD

**Issue by cc-morning** [blackbeam/mysql_async#188]
https://github.com/cc-morning/mysql_async/commit/fb2ca11475596e90e6bf9f8e949af4132632f920

```rust
let sql = "LOAD DATA LOCAL INFILE 'tmp' INTO TABLE `test` FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\r\n'";
let (sender, recv) = tokio::sync::mpsc::unbounded_channel();

let recv_task = tokio::spawn(async move {
    pool.get_conn().await.unwrap().load_data(sql, recv).await.unwrap();
});

sender.send(Bytes::from("a,b\r\nc,d")).unwrap();

drop(sender);
recv_task.await?;
```

**Comment by cc-morning** [comment]
Hello, do you need any help?

**Comment by blackbeam** [comment]
@cc-morning, hi. The impl is in #190.

It is based on `Stream<io::Result<Bytes>>` to not to stick to a particular channel implementation (you can get one using [`ReceiverStream`](https://docs.rs/tokio-stream/0.1.8/tokio_stream/wrappers/struct.ReceiverStream.html)).

This change is breaking, so I won't release it until I fix few other issues. Please use git dependency, if necessary.

**Comment by cc-morning** [comment]
> @cc-morning, hi. The impl is in #190.
> 
> 
> 
> It is based on `Stream<io::Result<Bytes>>` to not to stick to a particular channel implementation (you can get one using [`ReceiverStream`](https://docs.rs/tokio-stream/0.1.8/tokio_stream/wrappers/struct.ReceiverStream.html)).
> 
> 
> 
> This change is breaking, so I won't release it until I fix few other issues. Please use git dependency, if necessary.
> 
> 
> 
> 

It was fantastic, he does work better than channel. Thank you very much for your work!
