### ISSUE TITLE
Dependencies for this crate

### ISSUE THREAD

**Issue by mwdowns** [blackbeam/mysql_async#19]
Sorry if this is not the correct channel to use for something like this. If it is not, what is a better way to get answers?

For your crates.io page you say that I should put mysql_async in the dependencies, but in your documentation page on https://docs.rs/mysql_async/0.12.2/mysql_async/ you say I should but mysql in the dependencies. I don't really understand which one I should use. Also you ask for extern crate futures and tokio_core. Do I add those in my dependencies as well?

**Comment by blackbeam** [comment]
Hi.

> For your crates.io page you say that I should put mysql_async in the dependencies, but in your documentation page on https://docs.rs/mysql_async/0.12.2/mysql_async/ you say I should but mysql in the dependencies. I don't really understand which one I should use.

Yeah, it's a copy-pase error. You should use `mysql_async` crate as a dependency.

> Also you ask for extern crate `futures` and `tokio_core`. Do I add those in my dependencies as well?

Yes. You usually need both of them.
