### ISSUE TITLE
Query methods that accept byte slices (not just str)

### ISSUE THREAD

**Issue by glittershark** [blackbeam/mysql_async#194]
Oddly enough, it appears that MySQL is perfectly happy to accept queries that include invalid utf8 (eg for literals for blobs) - unfortunately, it's currently impossible to make those queries using `mysql_async`, since the query methods all accept `&str`. Would you be willing to accept a patch to add equivalent methods to `query` and `prepare` that accept `&[u8]` as well? Maybe `query_bytes` and `prepare_bytes`?

**Comment by blackbeam** [comment]
Sure. But I wonder can we make it without increasing the API surface e.g. using `T: AsRef<[u8]≥`.

**Comment by glittershark** [comment]
I'd be worried about that being a breaking change since `AsRef<[u8]> + AsRef<str>` is more restrictive than `AsRef<str>` Could introduce a new sealed trait for it (to accept either, but not require both), or just take the breaking change since mysql_async is 0.x anyway. Up to you.

**Comment by glittershark** [comment]
Speaking of breaking changes, adding these methods to `Queryable` is also a breaking change since it's not sealed - how do you feel about that?

**Comment by blackbeam** [comment]
Next release will be breaking anyway (because of changes in the `LOCAL INFILE` API).

**Comment by glittershark** [comment]
So would you rather go with `AsRef<str> + AsRef<[u8]>`?

**Comment by blackbeam** [comment]
Oh. I thought of just using `AsRef<[u8]>` instead of `AsRef<str>` but now I find the second option more preferable (actually because of `Cow<str>` that I use a lot).

I wonder how many users actually supplied their own types that impl'd `AsRef<str>` 🤔
