### ISSUE TITLE
Request: feature to make use of rustls instead of native-tls

### ISSUE THREAD

**Issue by GlenDC** [blackbeam/mysql_async#195]
Hi! First of all a giant amount of gratitude for all of you for providing this crate.
It worked out of the box and was very pleasant to use.

With that being said. This is currently my only dependency through which
I require native-tls support, all other dependencies that I use do already allow `rustls` support.
Is it on the roadmap already to provide `rustls` support, be it an opt-in feature. It would allow
me to simplify my production processes.

If there is something I can help in this regards to assist in making this happen you can let me know as well.
And once again, thanks for developing and maintaining this crate, it's fantastic :)

**Comment by blackbeam** [comment]
Hi. Yeah, it's on the roadmap, but I'm sure when I would be able to ship it (not much spare time at the moment).

> If there is something I can help in this regards to assist in making this happen you can let me know as well.

It would be great if someone could come up with a PR. Actually blackbeam/rust-mysql-simple#295 covers all the details and may be used as a reference implementation.

**Comment by GlenDC** [comment]
Ok fantastic, going to put it on my personal backlog. Will see if I get to it, thanks for giving me the pointer!
For now it's not a blocker, but as I said, given it is the only dependency it would be a shame if in the end it is. the reason I need to support the native tls requirements just because of it.

Also once again for making this crate!

**Comment by TobiasDeBruijn** [comment]
PR is ready I'd say! I need to get OpenSSL out of my dependency tree, but do want to switch to the async version of the mysql crate. Awesome work on both!
