### ISSUE TITLE
Column of Statement  support column comment?

### ISSUE THREAD

**Issue by easykoala** [blackbeam/mysql_async#197]
Column of Statement  support column comment? thanks.

**Comment by blackbeam** [comment]
Hi.

Can't understand what do you mean by that. Could you please give an example?

**Comment by easykoala** [comment]
let stmt = conn.prep(format!("select * from {}", &table_name)).await?;
    let mut cols: Vec<String> = Vec::new();
    for col in stmt.columns() {
        println!("{:?}", (&col.name_str(), col.column_type(), col.column_length()));
        cols.push(col.name_str().to_string());
        // I want to get the column comment, how?
        ......
    }

**Comment by blackbeam** [comment]
Oh, I see. No, server does not provide this information to a client when it prepares a statement. `stmt.columns()` is not a general columns definitions, but a technical one.

I suggest you to use something like

```
SELECT a.COLUMN_NAME, a.COLUMN_COMMENT
FROM information_schema.COLUMNS a 
WHERE a.TABLE_NAME = ?;
```

**Comment by easykoala** [comment]
Oh, I see，Thanks.
