### ISSUE TITLE
does mysql_async uses COM_RESET_CONNECTION?

### ISSUE THREAD

**Issue by brunoqc** [blackbeam/mysql_async#2]
The test 'conn::test::should_reset_the_connection' fails on mariadb 10.1.19 since [it's not implemented yet](https://jira.mariadb.org/browse/MDEV-10340) and I was wondering if I could still use mysql_async with mariadb.

**Comment by blackbeam** [comment]
Wow. I thought it's supported.
I will fix this with something similar to `(hard|soft)_reset` as implemented in mysql crate.

**Comment by blackbeam** [comment]
> I was wondering if I could still use mysql_async with mariadb.

You can, because it is used only in `should_reset_the_connection` test at the moment.

**Comment by blackbeam** [comment]
Version, reported by latest stable mariadb is 5.5.5, so driver should perform hard reset and everything should be OK.
