### ISSUE TITLE
No way of setting TCP_NODELAY

### ISSUE THREAD

**Issue by jonhoo** [blackbeam/mysql_async#20]
As demonstrated in https://github.com/blackbeam/rust-mysql-simple/pull/134, it's pretty important to be able to set `TCP_NODELAY` for the TCP sockets used for MySQL connections when queries and responses are small. It'd be great if an `OptsBuilder::tcp_nodelay` was available like in the synchronous `mysql` crate.

**Comment by blackbeam** [comment]
Closed by 25b7546 and published in [v0.13.0](https://github.com/blackbeam/mysql_async/releases/tag/v0.13.0).
Thanks!
