### ISSUE TITLE
Binlog Stream cannot be disconnected

### ISSUE THREAD

**Issue by galeaspablo** [blackbeam/mysql_async#202]
When retrieving a binlog stream from a connection, the binlog stream has no way of getting disconnected (sending the COM_QUIT signal to MySQL -- not only closing the file handler). 

Furthermore, if the stream's connection came from a pool, the pool panics when it gets dropped because its invariants are not respected. Namely, the pool still holds a count from the binlog connection, which it should decrease (but doesn't) when the binlog connection was dropped.

**Comment by galeaspablo** [comment]
I've made a PR. Please see [#201](https://github.com/blackbeam/mysql_async/pull/201)

**Comment by blackbeam** [comment]
#201 merged, so closing. Thanks!
