### ISSUE TITLE
Missing way to drop a statement

### ISSUE THREAD

**Issue by weiznich** [blackbeam/mysql_async#210]
[`Opts::stmt_cache_size`](https://docs.rs/mysql_async/0.30.0/mysql_async/struct.Opts.html#method.stmt_cache_size) states:

> [Caveats](https://docs.rs/mysql_async/0.30.0/mysql_async/struct.Opts.html#caveats)
>
> If statement cache is disabled (stmt_cache_size is 0), then you must close statements manually.

`Statement` does not expose any method to close an created statement. This can easily lead to situations where the user exhausts the maximal number of prepared statements on configured on the database itself.

I would like to clarify if:

* The linked documentation is correct
* This a corresponding method is just missing from `Statement` (and it's up to the user to call it)
* `mysql_async` should automatically close `Statement` on drop on it's own

See https://github.com/weiznich/diesel_async/issues/26 for details

**Comment by blackbeam** [comment]
@weiznich, hi.
Please look at [Queryable::close](https://docs.rs/mysql_async/latest/mysql_async/prelude/trait.Queryable.html#tymethod.close).

**Comment by weiznich** [comment]
Thanks 
I know that I must missed something :+1:
