### ISSUE TITLE
couldn't convert NULL to None directly

### ISSUE THREAD

**Issue by winary** [blackbeam/mysql_async#218]
Thanks for such awesome library to use mysql!

I find one thing is weird, when using `first`,  if it came with `NULL`,  needs to use `Option<Option<_>>` to wrap my want type, or I will get an error, but if not a `NULL`, it works good with only one `Option`.

```
    // // this will panic
    // //   Couldn't convert Row { num: Null } to type u64
    // let num: Option<u64> = r"select null as num".first(&mut conn).await.unwrap();
    // println!("{:?}", num);

    let num: Option<Option<u64>> = r"select null as num".first(&mut conn).await.unwrap();
    println!("{:?}", num); // Some(None)

    let num: Option<u64> = r"select 3306 as num".first(&mut conn).await.unwrap();
    println!("{:?}", num); // Some(3306)
```

**Comment by blackbeam** [comment]
Hi.

`first` returns `Option<T>`, because there might be no rows. `T` is the column type, in your case it is `Option<u64>` because the column is nullable.
So the full return type of your `first` call is `Option<Option<T>>` where `Option<T>` is the column type.

**Comment by winary** [comment]
very clear. I got it
