### ISSUE TITLE
"Can't parse" error

### ISSUE THREAD

**Issue by magnusmanske** [blackbeam/mysql_async#219]
Did a `cargo update`, now my pool `get_conn` throws these errors:

```
Io(Custom { kind: UnexpectedEof, error: "can't parse: buf doesn't have enough data" })
```

Reverted to the previous `Cargo.toml`, works fine. Not sure if it's `mysql_async` or a dependent package, but I can't debug it more fine-grained at the moment.

**Comment by magnusmanske** [comment]
Here is the commit that broke things: https://github.com/magnusmanske/mixnmatch_rs/commit/b0115efacc2f9222b572d0e028b9a7b16014a240

**Comment by magnusmanske** [comment]
Might be related to https://gitter.im/rust-mysql/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by blackbeam** [comment]
@magnusmanske, hi.

> Did a `cargo update`, now my pool get_conn throws these errors

Could you please inspect Cargo.lock and give me old and new versions of updated `mysql_*` packages?

> Here is the commit that broke things: https://github.com/magnusmanske/mixnmatch_rs/commit/b0115efacc2f9222b572d0e028b9a7b16014a240

You meant that things goes OK if `cargo update` is performed but this commit is reverted?
Is it broken if `Cargo.toml` is reverted to the previous version an the commit is applyed?

**Comment by magnusmanske** [comment]
Yes, so
```
name = "mysql_common"
version = "0.29.1"
version = "0.29.2"
```
breaks things. Again, not sure this specific package is the root cause.

**Comment by magnusmanske** [comment]
0.29.1 works, 0.29.2 does not

**Comment by blackbeam** [comment]
Oh, forgot to ask your MySql version.

**Comment by magnusmanske** [comment]
10.1.39-MariaDB

**Comment by blackbeam** [comment]
@magnusmanske, could you please patch your `Cargo.toml` and reproduce this?
I'm interested in the updated error message.

```toml
[patch.crates-io]
regex = { git = "https://github.com/blackbeam/rust_mysql_common.git", branch = "de-error" }
```

**Comment by magnusmanske** [comment]
Am I doing something wrong?
```
> cargo update
    Updating git repository `https://github.com/blackbeam/rust_mysql_common.git`
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  patch for `regex` in `https://github.com/rust-lang/crates.io-index` failed to resolve

Caused by:
  The patch location `https://github.com/blackbeam/rust_mysql_common.git?branch=de-error` does not appear to contain any packages matching the name `regex`.
```

**Comment by blackbeam** [comment]
Oh, sorry. Copy-paste error.

```toml
[patch.crates-io]
mysql_common = { git = "https://github.com/blackbeam/rust_mysql_common.git", branch = "de-error" }
```

**Comment by magnusmanske** [comment]
I get a warning but it runs:
```
warning: Patch `mysql_common v0.29.2 (https://github.com/blackbeam/rust_mysql_common.git?branch=de-error#bf1ba6df)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
```

Seems to work with that patch...

**Comment by blackbeam** [comment]
Seems like it suggests to run `cargo update` to apply the patch. I believe for now it works on mysql_common v0.29.1 from crates.io.

**Comment by blackbeam** [comment]
Sorry for bothering you, but I couldn't reproduce this myself – tried on MariaDb 10.1.39 with two pools connected to two distinct db instances in multi-threaded tokio runtime – no luck.

**Comment by magnusmanske** [comment]
Update: I have run `cargo update` again today, now it seems to work. Maybe some odd incompatibility with another create. Anyway, seems to work now, thanks!
