### ISSUE TITLE
Batch delete by ids cannot be performed

### ISSUE THREAD

**Issue by qqliaoxin** [blackbeam/mysql_async#220]
"DELETE FROM orders WHERE order_id IN (:order_ids)"
        .with(params! { "order_ids" => ids, })
        .ignore(&mut conn)
        .await?;

There are problems:
If ids="1,2", the command cannot be executed

**Comment by blackbeam** [comment]
Hi. You are trying to give multiple values to a server where just a singe value expected.
Similar question answered in the following discussion: https://github.com/blackbeam/rust-mysql-simple/discussions/323

**Comment by qqliaoxin** [comment]
let mut conn = POOL.get_conn().await.unwrap();
    let order_ids: BaseModelIndex = request_body_serde_json(req).await.unwrap();

    let iter = order_ids.ids.iter().map(|s| s.to_string() + ","); // 迭代 并转换成 string

    let stringIds: String = iter.collect::<String>(); // 输出转字符
    let ids = &stringIds[..stringIds.len() - 1]; // 删除最后一个字符
    println!("ids::->{}", ids);

    "DELETE FROM orders WHERE order_id IN (:order_ids)"
        .with(params! { "order_ids" => ids, })
        .ignore(&mut conn)
        .await?;

    drop(conn);
------
But on delete, batch deletion cannot work

**Comment by qqliaoxin** [comment]
thank you
