### ISSUE TITLE
Alternative to priority_queue dependency

### ISSUE THREAD

**Issue by glittershark** [blackbeam/mysql_async#247]
dc78d2ddb5b37bdc0ace5d886678fefdffa349fc added a new dependency on the [priority-queue crate](https://docs.rs/priority-queue/1.3.1/priority_queue/), which is LGPL licensed - unfortunately, since Rust statically links all libraries and we distribute binaries to customers, this currently likely prevents us using mysql_async past that commit. Is there a world where you'd consider an alternative to that dependency, either permanently or via a feature flag, to allow non-copyleft-compliant use of mysql-async?

**Comment by blackbeam** [comment]
Oh, thanks for pointing it out!
@cloneable, could you please come up with a replacement?

**Comment by cloneable** [comment]
Sure! Technically, p-q is also licensed under MPL2, but I'm going to look for an alternative. Maybe the wait queue can be replaced with a tokio semaphore based queue. Re-insertion was the big issue.
