### ISSUE TITLE
Re-export "chrono" feature from mysql_common

### ISSUE THREAD

**Issue by lucypero** [blackbeam/mysql_async#252]
It would be great. We have to add `mysql_common` to our deps just to have the `chrono` feature, and that causes version syncing issues.

**Comment by blackbeam** [comment]
@lucypero, hi. What do you mean by "version syncing issues"?

**Comment by leontoeides** [comment]
I could not get chrono working.

- Added `mysql_async` to my crate
- Added `mysql_common` to my crate, with the `chrono` feature
- Matched my crate's `chrono` version with the `mysql_common` version of `chrono`
 
Rust is still giving errors that it can't find the trait to convert a `NaiveDateTime` to a `Value` or vice-versa.

Any suggestions?
