### ISSUE TITLE
pass prefer_socket=false is not effective

### ISSUE THREAD

**Issue by ouyanglin886** [blackbeam/mysql_async#253]
I have a server that is using the [TDSQL for MySQL](https://intl.cloud.tencent.com/product/dcdb) distribution database provided by Tencent Cloud.The TDSQL it's not support @@socket variable, but when I pass prefer_socket=false, he doesn't take effect。I think it may be caused by the following code：

        let settings: Option<Row> = if read_socket || read_max_allowed_packet || read_wait_timeout {
            self.query_internal("SELECT @@socket, @@max_allowed_packet, @@wait_timeout")
                .await?
        } else {
            None
        };
it's modify history:
<img width="933" alt="image" src="https://github.com/blackbeam/mysql_async/assets/9983369/ef2b893e-680a-441e-81df-8190d57d16ac">

**Comment by blackbeam** [comment]
Fixed in [v0.33.0](https://github.com/blackbeam/mysql_async/releases/tag/v0.33.0)

**Comment by mr-kelly** [comment]
Related: https://github.com/blackbeam/mysql_async/issues/322
