### ISSUE TITLE
not able to use mysql async inside a msps receiver

### ISSUE THREAD

**Issue by surajpayu** [blackbeam/mysql_async#27]
I want to listen on a receiver of a channel and for each element, i want to fire my query to database. Here is my code
```
fn sql_conn(handle : &tokio_core::reactor::Handle, rx:futures::sync::mpsc::Receiver<ChannelHolder>){
    let database_url = "mysql://suraj:Suraj@172.16.12.208:9106/yuka";
    let pool = my::Pool::new(database_url, handle);
    println!("Amount is 123");
    let f2 = rx.for_each(move|res| {
    let future = pool.clone().get_conn().and_then(|conn| {
        // Load payments from database.
        // conn.prep_exec("SELECT txnid, amount FROM txn_update where txnid=6959177461", ())
        conn.prep_exec("SELECT `key`, `value` FROM `config` where isactive=1", ())
    }).and_then(|result| {
        // Collect payments
        result.map_and_drop(|row| {
            let (txnid, value):(String, Option<String>) = my::from_row(row);
            match value.clone(){
                Some(x) => {
                    println!("key:value is {}: {}", txnid, x);
                    GLOBAL_CONFIG_CACHE.write().unwrap().insert(txnid.clone(), value.clone());
                },
                None    => println!("null value"),
            }
        })
    }).and_then(|(_ /* conn */, value1)| {
        // The destructor of a connection will return it to the pool,
        // but pool should be disconnected explicitly because it's
        // an asynchronous procedure.
        pool.disconnect().map(|_| value1)
    });
    handle.spawn(future.then(|_| Ok(())));
    Ok(())
    });
}
```

I am getting below error

error[E0507]: cannot move out of captured outer variable in an `FnMut` closure
   --> src/main.rs:559:17
    |
540 |     let pool = my::Pool::new(database_url, handle);
    |         ---- captured outer variable
...
559 |     }).and_then(|(_ /* conn */, value1)| {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^ cannot move out of captured outer variable in an `FnMut` closure

**Comment by blackbeam** [comment]
Hi and sorry for late response.

The problem here is unrelated to the library and [described on stackoverflow](https://stackoverflow.com/questions/28521637/how-can-i-move-a-captured-variable-into-a-closure-within-a-closure).
The closure that may be called multiple times here is the `for_each` handler on `rx`. So to fix this you need to clone and move pool into the last `and_then` handler.
