### ISSUE TITLE
Questions from Rust newbies

### ISSUE THREAD

**Issue by Vjze** [blackbeam/mysql_async#270]
When there are more than 12 query items, an error will be reported, but within 12 items, it can run normally. Why is this?
![1](https://github.com/blackbeam/mysql_async/assets/99671889/1880530e-04a7-4094-8304-f7b34a01027e)
![2](https://github.com/blackbeam/mysql_async/assets/99671889/5d6a06e3-47e0-4d30-b215-472a0e34904e)

https://github.com/blackbeam/mysql_async/assets/99671889/1e7cad5a-bbdd-464f-b4fc-be9a1c0495d3

**Comment by blackbeam** [comment]
Hi.
12 is a usual maximum arity for tuples that implements traits. Consider using something like this:

```rust
conn.query_map("...", |row: mysql_async::Row| {
    // do something with mysql_async::Row
});
```
