### ISSUE TITLE
Publish GetConn type

### ISSUE THREAD

**Issue by jonhoo** [blackbeam/mysql_async#28]
[`Pool::get_conn`](https://docs.rs/mysql_async/0.15.0/mysql_async/struct.Pool.html#method.get_conn) returns a `GetConn`, but that type is not public, and so it's impossible to write a function that takes whatever `Pool::get_conn` returns.

**Comment by blackbeam** [comment]
Hi!
Sorry for late response.
This issue was introduced by accident so thank you for pointing that out.
Fix published in v0.15.1
