### ISSUE TITLE
mysql_native_password or caching_sha2_password

### ISSUE THREAD

**Issue by adrianboston** [blackbeam/mysql_async#281]
More of a question

What auth plugin is this driver using:
mysql_native_password
aching_sha2_password

I see that the non async mysql offers both along with mysql_clear_password. 

I swapped to a different dbms server (with a newer version) and i cannot connect any longer. Tried several things but this seems to stand out. Although a new user was created with the mysql_native_password identification; still failed.

**Comment by blackbeam** [comment]
Hi. This driver supports `mysql_native_password`, `aching_sha2_password` as well as `mysql_old_password` (if secure_auth is disabled) and `mysql_clear_password` (if enable_cleartext_plugin is set)

**Comment by adrianboston** [comment]
Oh nice. I will test `caching_sha2_password` out. 

It turned out to be a different issue -- which others may run into.

It seems that the driver cannot connect to the local loopback. Setting the host as either `"localhost"` or `"127.0.0.1"` seems to consistently fail. 

The resolution was setting `bind-address = "0.0.0.0"` in `mysql conf.`

Noting that I do not use `mysql.sock` which may in fact accept `"localhost"` as the host.

The code in question
```
 let opts = mysql_async::OptsBuilder::default()
        .pool_opts(pool_opts)
        .user(Some(user))
        .pass(Some(passwd))
        // NOT USING FOR NOW .socket(Some("/path/to/mysql.sock")) 
        .ip_or_hostname(address)
        .tcp_port(port)
        .db_name(Some(name))
        ;

let pool = mysql_async::Pool::new(opts);
```

**Comment by adrianboston** [comment]
I believe this is closed, 
The resolution was setting `bind-address = "0.0.0.0"` in `mysql conf.`
