### ISSUE TITLE
`impl<T: AsRef<str> + Sized> From<T> for Opts` should not fail

### ISSUE THREAD

**Issue by NPN** [blackbeam/mysql_async#29]
The conversion from `AsRef<str> + Sized` to `Opts` panics if `from_url` returns `None`. But, according to the documentation of the `From` trait, `From` conversions should not fail.

Since this conversion can fail, when the `TryFrom` trait becomes stable (rust-lang/rust#33417), it should be used instead. That way, the caller can handle the error instead of experiencing a panic.

**Comment by blackbeam** [comment]
Fixed in [v0.17.0](https://github.com/blackbeam/mysql_async/releases/tag/v0.17.0).
