### ISSUE TITLE
Errors Don't Implement Sync Trait

### ISSUE THREAD

**Issue by tonygrue** [blackbeam/mysql_async#30]
(I'm using Rust for the first time, so apologies if this is known or intentional or a useless bug. Don't be afraid to tell me if I'm just doing it wrong.)

I'm implementing a web app with hyper and my returns are a Stream.  i.e. `Body::wrap_stream(GenerateStreamForResponse::new());`

One thing my `GenerateStreamForResponse` does is use mysql_async and along the way that can generate an error.  `Body::wrap_stream` however requires errors generated by the stream passed to it implement the `Sync` trait.  I see from the docs, that mysql_async errors do not impl Sync (https://docs.rs/mysql_async/0.15.1/mysql_async/errors/struct.Error.html).  Looking at the impl it looks like `error_chain!` is used, and looking at error_chain's issue tracker, it looks like this is known, and maybe intentional, but causing problems for users (https://github.com/rust-lang-nursery/error-chain/issues/240).

Perhaps I should just be translating these errors anyway, but it also looks like some other people are moving away from error_chain.  Should mysql_async move away from error_chain, should mysql_async add it's voice to request error_chain support Sync, or should I just translate my error?

One thing I can say for certain, is this is one of a million paper cuts I've hit as a new rust user.

**Comment by blackbeam** [comment]
Hi!
Yeah. Move to Failure is scheduled but you should translate errors until then.

**Comment by blackbeam** [comment]
Fixed in [v0.17.0](https://github.com/blackbeam/mysql_async/releases/tag/v0.17.0)
