### ISSUE TITLE
columns ref from `QueryResult`

### ISSUE THREAD

**Issue by hwchen** [blackbeam/mysql_async#31]
Hello,

Would it be ok to get a reference to columns in `QueryResult`, like https://docs.rs/mysql/14.2.0/mysql/struct.QueryResult.html#method.columns_ref ? This would be very useful to me, to be able to inspect the column types.

**Comment by blackbeam** [comment]
Hi.
Yeah definitely! I'll add it.

**Comment by blackbeam** [comment]
Fixed in v0.16.0

**Comment by hwchen** [comment]
Nice, thanks!
