### ISSUE TITLE
How to call a stored procedure and get multiple different result sets

### ISSUE THREAD

**Issue by cjon123** [blackbeam/mysql_async#312]
As the title says

**Comment by blackbeam** [comment]
@cjon123, hi. Have you tried to just call the procedure and iterate over result sets?

There is a [test](https://github.com/blackbeam/mysql_async/blob/master/src/conn/mod.rs#L1948) that uses multi-result procedures, but its purpose is to assert the proper error handling.

**Comment by cjon123** [comment]
@blackbeam Thank you very much, the problem has been solved！
