### ISSUE TITLE
bug: 'ERROR HY000 (1193): Unknown system variable 'socket''

### ISSUE THREAD

**Issue by mr-kelly** [blackbeam/mysql_async#322]
Our client is using a database called Tencent TxSQL database, which seems does not support `socket` variable.

<img width="1228" alt="image" src="https://github.com/user-attachments/assets/dff01a17-94d7-4e8e-ac18-fcdb93282d9f">

We attempted to set `prefer_socket=false` in the connection URL:

```
"mysql://{user}:{password}@{host}:{port}/{database}?prefer_socket=false"
```

But the problem still exist not resolved.

However, the issue remains unresolved.

How can prevent `mysql_async` trigger the `socket` keyword?

**Comment by mr-kelly** [comment]
Related: https://github.com/blackbeam/mysql_async/issues/253

**Comment by blackbeam** [comment]
@mr-kelly, hi. Can't reproduce this. Is it somehow possible that the `prefer_socket=false` part of the URL is truncated before given to the library? Can you inspect the actual `Opts` created and assert that `prefer_socket` is false?

**Comment by mr-kelly** [comment]
> @mr-kelly, hi. Can't reproduce this. Is it somehow possible that the `prefer_socket=false` part of the URL is truncated before given to the library? Can you inspect the actual `Opts` created and assert that `prefer_socket` is false?

Already fixed after upgrade the version to the newest
