### ISSUE TITLE
packet order incorrect

### ISSUE THREAD

**Issue by glademiller** [blackbeam/mysql_async#33]
While connecting to the same server referenced for this mysql simple issue https://github.com/blackbeam/rust-mysql-simple/issues/160 I get an error about unexpected packet order using mysql_async. My first thought is perhaps the feature that was added in mysql simple just hasn't been implement in mysql_async. I can get any extra details you need. This is using SSL without a server public certificate and with domain verification off.

**Comment by blackbeam** [comment]
Hi!
Yeah. I believe it's blackbeam/rust-mysql-simple#160.
I have plans to fix this until Jan 8.

**Comment by glademiller** [comment]
Great I'm glad a fix is in the roadmap.

**Comment by glademiller** [comment]
Thanks for the quick reply as well.

**Comment by blackbeam** [comment]
Support of `AuthSwitchRequest` is implemented in [v0.17.0](https://github.com/blackbeam/mysql_async/releases/tag/v0.17.0).
Could you please verify that this issue is now fixed?

**Comment by glademiller** [comment]
I will get verification done on Monday unfortunately I don't have access to the system in order to test over the weekend.

**Comment by glademiller** [comment]
Ok I downgraded to verify that this code base had the exact same error as before. Something is off. I am going to resurrect the old mysql simple version of this code to verify that it is indeed fixed after your changes there I think I tested but I want to double check.

**Comment by glademiller** [comment]
https://github.com/blackbeam/rust-mysql-simple/issues/161 was fixed could this be what would make my connection work in that code base?

**Comment by glademiller** [comment]
@blackbeam ok I guess I never tested your fix in 160 in mysql-simple and assumed since it was based on my code that fixed the issue for me when written inline it worked. As of right now I'm receiving the same issue on both implementations this one and mysql-simple.

ERROR 1045 (28000): Access denied for user 'user'@'ip' (using password: YES) }

**Comment by blackbeam** [comment]
Interesting..

Implementation is tested, at least with non-empty passwords, on MySql 8.0.11 for the following scenarios:
* `mysql_native_password` authentication
* `caching_sha2_password` authentication
* Auth switch from `mysql_native_password` to `caching_sha2_password`
* Auth switch from `caching_sha2_password` to `mysql_native_password`

Can you verify, just to be sure, that you can connect to your mysql instance using cli mysql client? I meant connect from the same host to the same database with the same user/pass combination.

If it'll work, then i'll try to recreate your environment more carefully.

**Comment by glademiller** [comment]
I haven't tried the CLI mysql client but I have used MySQL Workbench to connect over the same tunnel (I believe it would be the same implementation underneat).

**Comment by blackbeam** [comment]
Yeah. I'm sure it's the same.

Ok, than. I have a few questions:
* are you still using MySQL 5.7.21 server hosted on Windows?
* which authentication plugin is used for your MySql user? (I believe it's in the `plugin` column of the `mysql.user` table).
* which authentication plugin is the default authentication plugin in your MySql configuration? (btw can you reveal non-sensitive parts of your MySql configuration?)

**Comment by glademiller** [comment]
I will get you the answers to your first two questions and I think the third should be fine if you can tell me what you need.

Also just for a quick sanity check today I'm going to make sure I didn't somehow get the wrong credentials at some point before doing the above.

**Comment by glademiller** [comment]
@blackbeam good news I apparently was using the wrong username and password. We have had some configuration changes recently and my test script was out of date. I apologize for the false alarm on this it looks like everything is in order.

**Comment by blackbeam** [comment]
That's great 😅
