### ISSUE TITLE
Documentation Link Broken

### ISSUE THREAD

**Issue by colindjk** [blackbeam/mysql_async#4]
http://blackbeam.org/mysql_async/mysql_async/ currently isn't working.

**Comment by blackbeam** [comment]
Fixed. Thanks!

Also remember that [docs.rs](https://docs.rs) is available.

**Comment by BransonGitomeh** [comment]
still cant connect for me

**Comment by blackbeam** [comment]
Hi, @BransonGitomeh .

Old link will be removed from Cargo.toml on next release.
Please use [docs.rs](https://docs.rs/mysql_async) until then.
