### ISSUE TITLE
Future size

### ISSUE THREAD

**Issue by PvdBerg1998** [blackbeam/mysql_async#41]
I'm using this library with async-await, and I found that the futures created by my database implementation are gigantic. Is it normal that `.drop_exec` creates a 1kB future? The entirety of my manual tcp communication is less than half of that.

**Comment by blackbeam** [comment]
Hi.
That's interesting. How it was measured?

**Comment by PvdBerg1998** [comment]
Using `std::mem::size_of_val(&fut)`.

**Comment by PvdBerg1998** [comment]
Any update on this? I (temporarily?) fixed it by boxing some of my futures. It would be nice if this wasn't necessary ofcourse.

**Comment by blackbeam** [comment]
Yeah. I've managed to reduce size to ~300 bytes. Will try to release this soon.

**Comment by PvdBerg1998** [comment]
That's great! I wonder what caused the other 700 bytes.

**Comment by blackbeam** [comment]
Size of `Conn` and size of `Row` (because of `SmallVec`).
