### ISSUE TITLE
wrongly parsed SQL

### ISSUE THREAD

**Issue by xNxExOx** [blackbeam/mysql_async#49]
`MySqlError(Server(ServerError { code: 1064, message: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'SELECT * FROM B\' at line 1", state: "42000" }))`
my sql is 
```sql
SELECT * FROM A;
SELECT * FROM B;
```
if I understand the API correctly I should be able to call `collect` twice on `QueryResult` to get rows from `A` on first call and rows from `B` on the second call.
Did I understand it wrongly?, or is it a bug?

**Comment by blackbeam** [comment]
Hi.

Yeah. Behavior is tested [here](https://github.com/blackbeam/mysql_async/blob/master/src/conn/mod.rs#L862). Not really sure why your server isn't happy. Could you, please share the actual code?

Also note that prepared statements can execute only one query at a time.

**Comment by xNxExOx** [comment]
```rs
pub async fn test(mysql_pool : &Pool) -> Result<(), mysql_async::error::Error>
{
    let con = await!(mysql_pool.get_conn().into_awaitable())?;
    const SQL :&str = "SELECT * FROM A WHERE guid = :guid;
SELECT * FROM B;";

    let guid = 1;
    let result = match await!(con.prep_exec(SQL, params!(guid)).into_awaitable()) {
        Err(err) => { println!("err: {:?}", err); return Err(err); }
        Ok(res) => res
    };
    println!("reched here");
    Ok(())
}
```

I generated these tables:
```sql
CREATE TABLE `db`.`A` (
  `guid` int(12) UNSIGNED NOT NULL,
  `a` int(12) UNSIGNED NOT NULL,
  `aa` int(12) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `db`.`B` (
  `guid` int(12) UNSIGNED NOT NULL,
  `b` int(12) UNSIGNED NOT NULL,
  `bb` int(12) UNSIGNED NOT NULL,
  `bbb` int(12) UNSIGNED NOT NULL,
  `bbbb` int(12) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `db`.`A`
  ADD PRIMARY KEY (`guid`);
ALTER TABLE `db`.`B`
  ADD PRIMARY KEY (`guid`);
```
error message is printed:
`err: Server(ServerError { code: 1064, message: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'SELECT * FROM B\' at line 2", state: "42000" })`
My mysql server version is: `8.0.12`

**Comment by xNxExOx** [comment]
I tried to understand these `and_then`s but I really can not read that syntax :(

**Comment by blackbeam** [comment]
You're trying to prepare statement with multiple queries, but MySql, as i said earlier, wont allow that ([see here](https://stackoverflow.com/questions/20371677/execute-multiple-semi-colon-separated-query-using-mysql-prepared-statement)). For further info please consult the [Mysql documentation](https://dev.mysql.com/doc/refman/8.0/en/prepare.html).

Multiple result sets are for:
* plain queries (i.e. `conn.query("SELECT 1; SELECT 2;")`)
* stored procedures

> I tried to understand these and_thens but I really can not read that syntax :(

Yeah, i can't wait for async/await syntax stabilization. All this and_thens reminds me old-fashioned javascript promises' `then(_).then(_)` chains.

**Comment by xNxExOx** [comment]
oh thanks for explanation.
but because `query` does not support params I think I keep selects separate.
