### ISSUE TITLE
Usage of tokio::spawn

### ISSUE THREAD

**Issue by PvdBerg1998** [blackbeam/mysql_async#50]
Hello. I'm using your crate with futures 0.3 and a custom threadpool. When updating my dependencies, I saw you pushed a commit which uses `tokio::spawn`: https://github.com/blackbeam/mysql_async/commit/5dd7d45af1184813f3bd7b864a69d7e53e8c3848.

Am I correct in thinking this will panic since I haven't set up a tokio executor?
Are there any other places that are hardcoded to use tokio's threadpool? (Couldn't find any.)

This would cripple the flexibility of the crate by requiring a fut 0.1 tokio executor to be used.

**Comment by PvdBerg1998** [comment]
I've experimented a bit and it doesn't seem to panic. Maybe it will just fail quietly? Anyway, a "maybe" is not very comforting.

**Comment by PvdBerg1998** [comment]
Any ideas on this issue @blackbeam ?

**Comment by blackbeam** [comment]
Hi. I'm quite busy for last few weeks and didn't look into it yet.

Looks like `spawn` calls that i should afraid of is within `Drop` impl for `Conn` and within `Pool::disconnect`, because everything else is in task context.

I'll look into it a bit more and reintroduce queue of dropping connections if needed.

**Comment by PvdBerg1998** [comment]
No worries! Thanks for the continued support :smiley:

**Comment by PvdBerg1998** [comment]
Am I correct in seeing that if there is no tokio executor (I'm using a custom one), the cleanup code will never be called and the error ignored? (See conn::disconnect)

This seems like less than optimal behaviour.
