### ISSUE TITLE
QueryResult::collect ought to from_row_opt, not from_row

### ISSUE THREAD

**Issue by jkoudys** [blackbeam/mysql_async#51]
Looking here:
https://github.com/blackbeam/mysql_async/blob/2c261cf0a9f0a044fe417124f116dd94f3e07189/src/queryable/query_result/mod.rs#L232

Compare to the standard Iterator::collect method: https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.collect

> a collection of Result<T, E> can be thought of as single Result<Collection<T>, E>. See the examples below for more.

The `collect` method will, however, always panic if one of the rows fails to convert. This makes the trait unusable in any application where you're listening for incoming connections.

**Comment by blackbeam** [comment]
Hi.

This is intentional. `from_row` should never fail if user knows his schema, which is, most likely, true.
I think, however, that it's reasonable to introduce `try_collect` to cover other cases.

Until then you can define your own helper using `QueryResult::reduce`

**Comment by blackbeam** [comment]
Fix published as [v0.19.1](https://github.com/blackbeam/mysql_async/releases/tag/v0.19.1)
