### ISSUE TITLE
affected_rows return 1 even if multiple rows are INSERTed

### ISSUE THREAD

**Issue by xNxExOx** [blackbeam/mysql_async#52]
```rs
mysql_pool : &Pool;

    const SQL : &str = "INSERT INTO cards (owner, ismastercard, cardtemplate, upgradecount, \
    upgradelevel, istradeable, isstarter, idcardpool, idlimitedpool, \
    chargeCard1, chargeCard2, chargeCard3) VALUES \
    (:owner, :ismastercard, :cardtemplate, 0, 0, 0, :isstarter, \
    :idcardpool, :idlimitedpool, 0, 0, 0)";
    for d in stater_decks {
        let len = d.cards.len();
        let is_tutorial= (d.card_pool == CardPool::Tutorial as u8) as u8;
        let card_pool= d.card_pool;
        let limited_pool= d.limited_pool;
        let c : Vec<(u32, u8, u32, u8, u8, u8)> = d.cards.iter().map(|c| (guid, 0, c.card_id, is_tutorial, card_pool, limited_pool)).collect();
        let con = await!(mysql_pool.get_conn().into_awaitable())?;
        trace!("{:?}", c);
        let result = await!(con.batch_exec(SQL, c).into_awaitable())?;
        if result.affected_rows() != len as u64 {
            error!("can not create starter deck cards, affected rows:{:?} expected:{}", result.affected_rows(), len);
```
logs:
```
 TRACE [(55, 0, 253, 1, 2, 2), (55, 0, 287, 1, 2, 2), (55, 0, 288, 1, 2, 2), (55, 0, 354, 1, 2, 2), (55, 0, 379, 1, 2, 2), (55, 0, 673, 1, 2, 2), (55, 0, 700, 1, 2, 2)]
 ERROR can not create starter deck cards, affected rows:1 expected:7
```
Can you please point me out to what I am doing wrong? Or is this a bug?

Is there any better way to ask questions specific to this crate, to not create issues here if the problem can be on my side?

**Comment by blackbeam** [comment]
Hi.
This result is expected because `Conn::affected_rows` returns number of affected rows, as reported by MySql server after the latest executed query, and the last executed query is (on the last iteration over `c`) your `INSERT ...` statement that inserts one row.

> Is there any better way to ask questions specific to this crate, to not create issues here if the problem can be on my side?

I'm not sure about that. There exist stackoverflow where @shepmaster does the great job of answering mysql-crate-related questions. AFIAK there is no way to subscribe to a conjunction of stackoverflow tags, so I'm monitoring stackoverflow on once-per-month basis.

**Comment by xNxExOx** [comment]
oh, so it will convert 
`INSERT ... VALUES(:x)` where x is vector to:
`INSERT ... VALUES(x0)`, `INSERT ... VALUES(x1)`, `INSERT ... VALUES(x2)`, ... 
instead of `INSERT ... VALUES(x0), (x1), (x2),...`
this seems wrong, and slow. Is there a way to convert it to single insert? (other than building the sting manually, which I will end up doing if there is no other way)

**Comment by blackbeam** [comment]
It's server limitation, unfortunately.
Related issue: [blackbeam/rust_mysql_simple#59](https://github.com/blackbeam/rust-mysql-simple/issues/59)
