### ISSUE TITLE
Strange behavior when `PoolConstraints::min` is 0

### ISSUE THREAD

**Issue by jonhoo** [blackbeam/mysql_async#57]
I accidentally set `PoolConstraints::min` to `0` (and max to 1), and this causes the library to continuously drop and start connections as new queries are issued. That seems counterintuitive. Should this be asserted against in `PoolConstraints::new`?

**Comment by blackbeam** [comment]
This reminds me an old issue in rust where the value was pushed to the stack in a loop and the stack was on it's boundary.

Thanks for report. I'll introduce a kind of "inactive connection timeout" for this.
