### ISSUE TITLE
Publish GetConn and friends again

### ISSUE THREAD

**Issue by Darksonn** [blackbeam/mysql_async#58]
In issue #28 the `GetConn` type was supposedly published, but as of version 0.19.0 it is not published.

Besides the `GetConn` type, there's also a `DisconnectPool` future, which similarly deserves to be published.

**Comment by blackbeam** [comment]
Ah! Sorry for that. Will publish asap.

**Comment by blackbeam** [comment]
Published as [v0.19.1](https://github.com/blackbeam/mysql_async/releases/tag/v0.19.1)
