### ISSUE TITLE
breaking change: SslOpts::new constructor is gone in version `0.19.1`

### ISSUE THREAD

**Issue by mitrandir77** [blackbeam/mysql_async#59]
Looking at [commit that removes it](https://github.com/blackbeam/mysql_async/commit/bb62c33e4bb346f7e625be38e22c493a88c99ccd#diff-b3230d04866da1c605fe1bf2fead0532L43) this doesn't look like intentional breaking change to the API. I believe this should warrant the major version bump.

**Comment by blackbeam** [comment]
Removed by accident, sorry.
Changes like this definitely deserve version bump corresponding to the semver spec.
