### ISSUE TITLE
Additional LocalInfileHandler implementation

### ISSUE THREAD

**Issue by travismiller** [blackbeam/mysql_async#60]
The existing example of using `LocalInfileHandler` doesn't actually read a file. Below, I've included an example that does.

https://github.com/blackbeam/mysql_async/blob/54dbffaaa108cb5a0c97862d0f759d2b9a0060b5/src/local_infile_handler/mod.rs#L45-L51

```rust
struct InfileHandler;

impl LocalInfileHandler for InfileHandler {
    fn handle(
        &self,
        file_name: &[u8],
    ) -> Box<Future<Item = Box<AsyncRead + Send>, Error = my::error::Error> + Send> {
        let path = std::str::from_utf8(file_name)
            .unwrap() // TODO: not panic
            .to_owned();

        let future = tokio::fs::File::open(path)
            .map(|file| Box::new(file) as Box<_>)
            .map_err(|e| e.into());

        Box::new(future)
    }
}

// let mut opts = my::OptsBuilder::from_opts(&*database_url);
// opts.local_infile_handler(Some(InfileHandler {}));

```

**Comment by blackbeam** [comment]
Oh. I'll rewrite [`WhiteListFsLocalInfileHandler`](https://docs.rs/mysql_async/0.19.1/mysql_async/struct.WhiteListFsLocalInfileHandler.html) using `tokio::fs` (there was no `tokio::fs` when it was implemented).

Also note that with your simple example you should be aware of [security issues with LOAD DATA LOCAL](https://dev.mysql.com/doc/refman/8.0/en/load-data-local.html).

**Comment by travismiller** [comment]
Thanks! I see now that WhiteListFsLocalInfileHandler actually had a file reading mechanism.

**Comment by travismiller** [comment]
@blackbeam I've gone ahead and made PR #61 for this.

**Comment by blackbeam** [comment]
Thanks for your contribution.
