### ISSUE TITLE
Taking a synchronous lock in async code

### ISSUE THREAD

**Issue by jonhoo** [blackbeam/mysql_async#64]
`Pool::get_conn` (or, more precisely, the [`GetConn` future](https://github.com/blackbeam/mysql_async/blob/2c261cf0a9f0a044fe417124f116dd94f3e07189/src/conn/pool/futures/get_conn.rs#L30)) forwards onto [`Pool::poll`](https://github.com/blackbeam/mysql_async/blob/301cb80698811402d637b40f137d82844dfb523b/src/conn/pool/mod.rs#L289). `Pool::poll` in turn calls [`Pool::with_inner`](https://github.com/blackbeam/mysql_async/blob/301cb80698811402d637b40f137d82844dfb523b/src/conn/pool/mod.rs#L193), which takes [this `std::sync::Mutex`](https://github.com/blackbeam/mysql_async/blob/301cb80698811402d637b40f137d82844dfb523b/src/conn/pool/mod.rs#L53). This is hugely problematic in asynchronous code, as blocking on taking that lock will hold up the I/O reactor and the processing of any other futures scheduled on the same worker thread. This manifests especially at very high load, as [this flamegraph](https://jon.thesquareplanet.com/share/noria-client.svg) shows.

There are many possible ways to fix this, but the best one would probably be to find a way to avoid the lock altogether and switch to something like a [`crossbeam` queue](https://docs.rs/crossbeam/0.7/crossbeam/queue/index.html) of "available" connections and an `AtomicBool` for the `closed` flag. An alternative would be to use a futures-aware `Mutex` like [`tokio_sync::Lock`](https://docs.rs/tokio-sync/0.1/tokio_sync/lock/index.html), though we'd then have to figure out how to make that work nicely with the synchronous interface on `Pool` (such as `take_conn`). Speaking of -- why do we even have those methods? In an asynchronous context, synchronous methods should probably not exist.

**Comment by jonhoo** [comment]
Or, a perhaps more obvious flamegraph: https://jon.thesquareplanet.com/share/noria-client-inv.svg

**Comment by jonhoo** [comment]
@blackbeam I'm working on a larger rewrite of `Pool` to fix this (and hopefully also #65)  :)

**Comment by blackbeam** [comment]
Hi, @jonhoo, and thanks for your work.

> Speaking of -- why do we even have those methods? In an asynchronous context, synchronous methods should probably not exist.

You definitely right about locks in async code and i just didn't think much about it at that moment.

> I'm working on a larger rewrite of Pool to fix this (and hopefully also #65)

That's great!

**Comment by jonhoo** [comment]
> > Speaking of -- why do we even have those methods? In an asynchronous context, synchronous methods should probably not exist.
> 
> You definitely right about locks in async code and i just didn't think much about it at that moment.

Ah, sorry, what I was asking here is whether having synchronous methods (i.e., things that don't return `Future`) on `Pool` was intentional? Is that something you'd want to be able to keep going forward?

**Comment by jonhoo** [comment]
I believe this was closed by #66.
