### ISSUE TITLE
Pool::disconnect blocks indefinitely

### ISSUE THREAD

**Issue by PvdBerg1998** [blackbeam/mysql_async#73]
I have a wrapper around a `Pool` object (using the new async update) which has a `disconnect` method:
```rust
pub async fn disconnect(&self) -> Result<()> {
    self.pool.clone().disconnect().await?;
    Ok(())
}
```
When I want to exit my program, I run this on my tokio runtime with `::block_on`. However, it never returns.

cc @jonhoo

**Comment by jonhoo** [comment]
So, from memory, this will wait until all currently-open connections are closed. Are you still holding on to connections elsewhere?

**Comment by PvdBerg1998** [comment]
I get one connection from the pool to test the connection, and then drop it. That should move it back into the pool, right?

I'm confused why the disconnect method would wait for the connections in the pool to close. Isn't that what this method should do? How else am I supposed to clean up my pool?

**Comment by jonhoo** [comment]
Hmm, yes, that should do it. Do you have some example code to play with?

Ah, `disconnect` does not _force_ a disconnect, it is more like tokio's `shutdown_on_idle`. If you have currently active connections, then those are allowed to finish before the pool is terminated. Forcibly terminating connections can easily lead to weird interactions, and would also require significantly more synchronization internally.

**Comment by PvdBerg1998** [comment]
I can't give an example atm but how should I be cleaning up a Pool properly? Is dropping enough? I could also drop my runtime first and then call disconnect on a new one but that's quite ugly. Is there an example of how this should be done? I couldn't understand the docs (I understand English is not the authors first language).

**Comment by jonhoo** [comment]
Dropping any connections you have received from the pool should be enough to make `Pool::disconnect` resolve. It'd be super helpful if you could produce a small reproducing example to dig into :)

**Comment by PvdBerg1998** [comment]
It still reproduces for me when I don't even use the `Pool` once.

```rust
pub struct Database {
    pool: Pool,
}

impl Database {
    pub async fn disconnect(&self) -> Result<()> {
        self.pool.clone().disconnect().await?;
        Ok(())
    }
}

fn main() {
    /* create pool */
    /* obtain runtime */
    runtime.block_on(database.disconnect());
    /* wait forever */
}
```

**Comment by PvdBerg1998** [comment]
Perhaps it's related to the clone I do? In my opinion that method should just take `&self`.

**Comment by blackbeam** [comment]
@PvdBerg1998, thanks for the example code. There is some probability that I've fixed it in #74.

@jonhoo, could you please look into it to make sure that i correctly understood your new pool implementation?

**Comment by PvdBerg1998** [comment]
@blackbeam Could you reopen this? I retried my code with your patch and it's still blocking.

**Comment by blackbeam** [comment]
@PvdBerg1998, how else your code differs [from this][1]?
Note that I've tried "by ref" version of disconnect with `self.pool.clone()` with no issues.

[1]: https://github.com/blackbeam/mysql_async/commit/8bfbf77e3c926cc59222e38e3ece6b4d6555adef#diff-d1344942d8599ae90513fe889bbcf58bR530

**Comment by PvdBerg1998** [comment]
It's hard to spot differences. My database is inside an Arc but that shouldn't make a difference. I'll update if I have more information.

**Comment by PvdBerg1998** [comment]
@blackbeam Sorry for the delay. In my code I take a connection and disconnect it, to test the connection.
```rust
pub async fn check_connection(&self) -> Result<()> {
    let conn = self.pool.get_conn().await?;
    conn.disconnect().await?;
    Ok(())
}
```

So my main is basically:

1. Start runtime
2. Test connection
3. Call disconnect
4. Hang

**Comment by blackbeam** [comment]
Thanks.

Should be fixed in 0dbf94b. Could you please test it?

**Comment by PvdBerg1998** [comment]
@blackbeam It works! 🎉 But seeing your patch it looks like I was doing something weird here. Is there a better way to test if the pool is connected properly? The pool seems to connect lazily so it won't error early if it can't connect.

**Comment by blackbeam** [comment]
> But seeing your patch it looks like I was doing something weird here.

Unfortunately your test most likely won't test anything, because already established connections [are only checked for expiration][1] because more trustworthy check will entail server roundtrip and so will be slow. I.e. pool is trying to be optimistic.

But even if you [ping][2] the connection in `check_connection` it's still possible that on the next call to `Pool::get_conn` pool will return broken connection simply because this call is _after_ `check_connection` call.

If you want to get actually alive connection whatever it takes than I suggest you to make your own wrapper for get_conn:

```rust
pub async fn get_conn(&self) -> Result<()> {
    let conn = self.pool.get_conn().await?;
    conn.ping().await?
}
```

[1]: https://github.com/blackbeam/mysql_async/blob/0dbf94b6fb264a37267209986368dbf9b5abbf33/src/conn/pool/mod.rs#L379
[2]: https://github.com/blackbeam/mysql_async/blob/0dbf94b6fb264a37267209986368dbf9b5abbf33/src/queryable/mod.rs#L75
