### ISSUE TITLE
How to express queries with IN passing parameters

### ISSUE THREAD

**Issue by glademiller** [blackbeam/mysql_async#76]
I have a query that needs to pass a Vec<String> to the query as a parameter in order to use IN. I haven't found a way to express this. How can this be done or does there need to be an enhancement made?

**Comment by blackbeam** [comment]
Hi!

It's partially discussed [here][1] and [here][2].

tl;dr – you need a query builder.

I'm starting to think that it's OK to include simple knex-like query builder into this driver.

[1]: https://github.com/blackbeam/rust-mysql-simple/issues/153
[2]: https://github.com/blackbeam/rust-mysql-simple/issues/85

**Comment by glademiller** [comment]
Thanks for the quick reply on this. The solutions in those two links will work ok for now. Should I go ahead and close this out?

**Comment by pimeys** [comment]
We're writing our query builder for this and would like to have more eyes and help with it if you're interested @glademiller 

- the sync version: https://github.com/prisma/prisma-query/
- the upcoming async/await version: https://github.com/prisma/prisma-query/tree/async-await

**Comment by blackbeam** [comment]
Closing this for now. Feel free to reopen.
