### ISSUE TITLE
Support info field on `OkPacket`

### ISSUE THREAD

**Issue by liamcurry** [blackbeam/mysql_async#93]
It would be useful to have access to `OkPacket::info_ref` similar to `last_insert_id` and `affected_rows`. For reference: https://docs.rs/mysql_common/0.20.1/mysql_common/packets/struct.OkPacket.html#method.info_ref

I am needing this info to parse the rows matched by an `UPDATE` query, that won't necessarily be affected.

**Comment by blackbeam** [comment]
Available in [v0.22.0](https://github.com/blackbeam/mysql_async/releases/tag/v0.22.0).

**Comment by liamcurry** [comment]
Thank you!
